### ISSUE TITLE
FUSE inside jailmaker

### ISSUE THREAD

**Issue by qudiqudi** [Jip-Hop/jailmaker#1]
First issue yay! But it's more of a feature request.

I'm currently running a nextcloud-aio docker install inside a jail and have trouble using the built-in backup solution.
It doe not work because there is FUSE requiered. With LXC this has to be explicitly enabled is there any chance on getting this for nspawn to work?

For reference:

https://github.com/nextcloud/all-in-one/issues/273

https://forum.proxmox.com/threads/persistently-use-fuse-inside-of-lxc-container.95810/#post-415631

https://medium.com/myatus/quick-note-fuse-inside-proxmox-lxc-container-481706005a09

**Comment by Jip-Hop** [comment]
Thanks for reporting.

Perhaps you could try with `--bind=/dev/fuse` as additional `SYSTEMD_NSPAWN_USER_ARGS` in the config file.

Let me know if that works.

**Comment by qudiqudi** [comment]
It was as simple as that. I can confirm the Backup container now starts and backups work with BorgBackup.
Great and many thanks!

**Comment by Jip-Hop** [comment]
Glad to hear that! Thanks for trying and reporting back :)
