### ISSUE TITLE
IX-Systems and Jip-Hop installation instructions conflict

### ISSUE THREAD

**Issue by marshalleq** [Jip-Hop/jailmaker#107]
Confusingly IX Systems are saying that if you use their recommended installation folder / dataset it will upgrade to future versions nicely, then point us to this page which says to use a different folder / dataset.
Specifically [this link](https://www.truenas.com/docs/scale/scaletutorials/apps/sandboxes/) say to use /mnt/tank/sandboxes/ or /mnt/tank/jails and your instructions say to use /mnt/tank/jailmaker

I note that when I run the script with no options in the folder named sandboxes, the script complains that it is not in /mnt/tank/jailmaker.  I also tried changing the JAILS_DIR_PATH, but that seemed to present an error also.  Regardless of it being configurable, I think the instructions need to be in alignment.  It's very confusing being pointed here from there and finding out their instructions are wrong.  Probably...

it's further confusing that this site links me back to that page as instructions....

I'm going to change my dataset to jailmaker, but I'm not convinced that it will survive future version upgrades if I do, due to the way that page is worded.

I'm not sure yet, but possibly this only applies if you run the script without arguments, I just haven't got that far as I'm not sure yet what is the correct way to do it.  I guess I'll progress and see what goes wrong :(

**Comment by Jip-Hop** [comment]
Thanks for bringing this to my attention. The instructions by IX are not wrong, but not optimal either. All datasets you create will survive future version upgrades. So you won't have to worry about losing the dataset.

From the perspective of the TrueNAS SCALE system a dataset named jails, sandboxes or jailmaker is just a regular dataset, nothing special.

From the perspective of jailmaker hower it expects the dataset to be called jailmaker or else it will show this warning.

The IX instructions should be updated to reflect this.

**Comment by Jip-Hop** [comment]
@marshalleq could you please fix the documentation here by creating a pull request?

https://github.com/truenas/documentation/blob/master/content/SCALE/SCALETutorials/Apps/Sandboxes.md

**Comment by Jip-Hop** [comment]
[I created a PR for this](https://github.com/truenas/documentation/pull/2629).
