### ISSUE TITLE
Add hyperlink for systems-nspawn manual to the manual reference on your install page

### ISSUE THREAD

**Issue by marshalleq** [Jip-Hop/jailmaker#108]
You have hyperlinks for most things - I tried to google it and it came up with other stuff.  Then when I installed the default container, it showed me the link - perhaps it's specific to the container type, but I'd say it isn't really.

https://manpages.debian.org/bookworm/systemd-container/systemd-nspawn.1.en.html

It would have been helpful to me, so I'm suggesting it here.

Thanks.

**Comment by Jip-Hop** [comment]
Not sure what you mean. This link is already many times in the readme, is it not?
https://raw.githubusercontent.com/Jip-Hop/jailmaker/main/README.md

**Comment by marshalleq** [comment]
Well that one, is plain text.  I mean here. https://github.com/Jip-Hop/jailmaker

**Comment by Jip-Hop** [comment]
Please make a pull request if you think a link is missing somewhere.
