### ISSUE TITLE
Use semantic versioning for script version

### ISSUE THREAD

**Issue by mrstux** [Jip-Hop/jailmaker#125]
Hi,

I think it would be good if jailmaker used semantic versioning.

https://semver.org

ie major.minor.patch, where patch is incremented for fixes/improvements... minor is incremented for additional features, and major is incremented for breaking changes.

Looking at the release history, 1.1.4 should've been 1.2.0, and 1.1.5 should've been 1.3.0 ;)

It seems like prior to 1.1.4 everything was semantically versioned ;)

This would make it clearer to users how deeply they need to investigate the change notes... after all adding zfs dataset support is a fairly big deal, and there's a migration involved to take advantage of the feature... its not just a bug fix patch ;)

And when you remove deprecations, that  becomes a breaking change... which is the time to add other breaking changes. And then you have 2.0 ;)

**Comment by Jip-Hop** [comment]
Ah yes thanks for reminding me. My plan was to follow this scheme but I dropped the ball. For breaking changes I'll definitely bump the major version and I'll try to keep the minor version in mind.
