### ISSUE TITLE
Feature Request: allow a different text editor

### ISSUE THREAD

**Issue by Lockszmith-GH** [Jip-Hop/jailmaker#131]
jlmkr currently has [`nano` hardcoded](https://github.com/Jip-Hop/jailmaker/blob/9661f4ff19b44470319b7e258f562c8076405dda/jlmkr.py#L126) as the editor.

While it is a 'safe' choice, may I suggest to follow conventions already [acceptable in Debian](https://www.debian.org/doc/debian-policy/ch-customized-programs.html#editors-and-pagers)?
These should be even 'safer' as they follow system expectations.

1. If `VISUAL` environment vairable exist, and the command exists, use `$VISUAL` as the editor.
2. otherwise, if `EDITOR` environment vairable exist, and the command exists, use `$EDITOR` as the editor.
3. otherwise, if `/usr/bin/editor` exists and it is executable, use it as the editor (this is controlled by debian's `update-alternatives` system.
4. otherwise default to `nano`. (although on TrueNAS SCALE, a debian system, (2) will always be present.

This would allow using a different editor for those allergic to nano (sorry, old school here) who bother to modify their system and install another editor.

Further references:
- https://unix.stackexchange.com/a/42765/138012
- https://unix.stackexchange.com/a/4861/138012

**Comment by Jip-Hop** [comment]
On my SCALE instance I don't see any value for `EDITOR` in my environment. Running `printenv | grep -i edit` while logged in as root user via SSH doesn't return anything.

I'm not sure it's worth all the code to implement these 4 cases with fallbacks. I think the jailmaker code as already way to many lines as it is... But maybe using `/usr/bin/editor` instead of the hardcoded `nano` would satisfy this request without complicating things?

Or use `EDITOR` if set and fallback to `nano` when empty?

Feel free to provide a PR.

**Comment by Lockszmith-GH** [comment]
EDITOR is an optional envrionment variable a user sets for themselves, it does not exist by default.
That's just common practice.

I agree that `editor` will work for anyone (like me) who updates the `update-alternative` configuration (after every reboot 🤭)

A short version fo the logic described by debian documentaion is prefer `$EDITOR` with a fallback to `/usr/bin/editor`

**Comment by mrstux** [comment]
I understand the reasoning, and agree, but I also think its very useful defaulting to nano on a TrueNAS default install.

It seems to me that supporting the EDITOR environment variable is perhaps the cleanest way to allow power users to set some other editor..

The non-power users will be most happy with nano imo

**Comment by Lockszmith-GH** [comment]
Keep in mind that /usr/bin/editor is mapped to nano by default on most debian system, and this is true to TrueNAS SCALE as well, that means non need of mentioning nano specifically in the code.

**Comment by Jip-Hop** [comment]
Please test PR https://github.com/Jip-Hop/jailmaker/pull/157. The text editor is used in 2 cases: during interactive create to provide the template text and during edit.

**Comment by Lockszmith-GH** [comment]
The implementation is simple, and works as expected.

**Comment by Jip-Hop** [comment]
Closed by https://github.com/Jip-Hop/jailmaker/pull/157. Thanks @maxnordlund!
