### ISSUE TITLE
Machine not created/started

### ISSUE THREAD

**Issue by ZestyChicken** [Jip-Hop/jailmaker#14]
Forgive my limited IT skills to figure out the problem. I followed the instructions and while the jail was created, a machine was not. The log files show a lot of errors:

-- Journal begins at Tue 2023-04-18 03:04:40 CDT, ends at Tue 2023-04-18 20:39:38 CDT. --
Apr 18 20:24:47 truenas systemd[1]: Starting My nspawn jail myjail [created with jailmaker]...
Apr 18 20:24:47 truenas systemd[1]: Started My nspawn jail myjail [created with jailmaker].
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: systemd 247.3-7+deb11u1 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPT>
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Detected virtualization systemd-nspawn.
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Detected architecture x86-64.
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Detected first boot.
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: 
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Welcome to Debian GNU/Linux 11 (bullseye)!
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: 
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Set hostname to <myjail>.
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Initializing machine ID from container UUID.
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Failed to create control group inotify object: Too many open files
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Failed to allocate manager object: Too many open files
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: [!!!!!!] Failed to allocate manager object.
Apr 18 20:24:47 truenas systemd-nspawn[1508324]: Exiting PID 1...
Apr 18 20:24:47 truenas systemd[1]: jlmkr-myjail.service: Main process exited, code=exited, status=255/EXCEPTION
Apr 18 20:24:47 truenas systemd[1]: jlmkr-myjail.service: Failed with result 'exit-code'.
Apr 18 20:28:39 truenas systemd[1]: Starting My nspawn jail myjail [created with jailmaker]...
Apr 18 20:28:39 truenas systemd[1]: Started My nspawn jail myjail [created with jailmaker].
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: systemd 247.3-7+deb11u1 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPT>
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Detected virtualization systemd-nspawn.
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Detected architecture x86-64.
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Detected first boot.
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: 
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Welcome to Debian GNU/Linux 11 (bullseye)!
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: 
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Set hostname to <myjail>.
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Initializing machine ID from container UUID.
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Failed to create control group inotify object: Too many open files
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Failed to allocate manager object: Too many open files
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: [!!!!!!] Failed to allocate manager object.
Apr 18 20:28:39 truenas systemd-nspawn[1533219]: Exiting PID 1...
Apr 18 20:28:39 truenas systemd[1]: jlmkr-myjail.service: Main process exited, code=exited, status=255/EXCEPTION
Apr 18 20:28:39 truenas systemd[1]: jlmkr-myjail.service: Failed with result 'exit-code'.
Apr 18 20:31:48 truenas systemd[1]: Starting My nspawn jail myjail [created with jailmaker]...
Apr 18 20:31:48 truenas systemd[1]: Started My nspawn jail myjail [created with jailmaker].
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: systemd 247.3-7+deb11u1 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPT>
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: Detected virtualization systemd-nspawn.
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: Detected architecture x86-64.
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: Detected first boot.
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: 
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: Welcome to Debian GNU/Linux 11 (bullseye)!
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: 
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: Set hostname to <myjail>.
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: Initializing machine ID from container UUID.
Apr 18 20:31:48 truenas systemd-nspawn[1547125]: Failed to create control group inotify object: Too many open files

**Comment by Jip-Hop** [comment]
Sorry to hear you're having trouble using jailmaker. I haven't seen this error before but I doubt it's a jailmaker specific issue. Have you tried rebooting?

Have you searched online for: "Failed to create control group inotify object: Too many open files"?

**Comment by ZestyChicken** [comment]
Fixed my own problem:
Go to system settings > advanced > syctl:
fs.inotify.max_user_watches
1048576

fs.inotify.max_user_instances
1024

**Comment by Jip-Hop** [comment]
Great!

**Comment by haldi4803** [comment]
Oh... thanks for that info.
Had that [issue before](https://www.truenas.com/community/threads/too-many-open-files-messages-when-tail.114008/#post-811204) with about 10 apps running, but didnt use persistent config through advanced page then.
