### ISSUE TITLE
The dataset permissions configured in TrueNAS affect the jail permissions

### ISSUE THREAD

**Issue by nguypaul** [Jip-Hop/jailmaker#15]
Hello,
After many hours of troubleshooting strange issues within my jail, I finally pinpointed my issues down to permissions. I resolved my issues by changing the location of the jlmkr.py script to a different dataset. Once I moved the script to a different dataset and created a new jail, everything is working correctly.  The dataset with issues has SMB shares and ACLs, which I think may be the cause.

Here is some of the behaviors:

1. apt-get update errors with Temporary failure resolving deb.debian.org

> root@testjail:~# apt-get update
Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.

Looking at /etc/resolv.conf, has incorrect permissions:

> root@testjail:~# ls -l /etc/resolv.conf 
-rwx------ 1 root root 37 Apr 30 13:50 /etc/resolv.conf

Running chmod 644 /etc/resolv.conf resolves the issue and running apt-get update works.

2. apt-get install iptables throws error.

> root@testjail:~# apt-get install iptables
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  firewalld kmod
The following NEW packages will be installed:
  iptables
0 upgraded, 1 newly installed, 0 to remove and 23 not upgraded.
7 not fully installed or removed.
Need to get 0 B/382 kB of archives.
After this operation, 2,582 kB of additional disk space will be used.
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 11726 files and directories currently installed.)
Preparing to unpack .../iptables_1.8.7-1_amd64.deb ...
Unpacking iptables (1.8.7-1) ...
dpkg: error processing archive /var/cache/apt/archives/iptables_1.8.7-1_amd64.deb (--unpack):
 unable to open '/usr/lib/x86_64-linux-gnu/xtables/libip6t_hl.so.dpkg-new': No such file or directory
Errors were encountered while processing:
 /var/cache/apt/archives/iptables_1.8.7-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

I was unable to determine the actual cause for the installation of iptables to error out, but once I moved the jailmaker script to a different dataset and created a new jail, everything is working as expected now.

**Comment by Jip-Hop** [comment]
Glad to hear it's working and thanks for posting! The first step of the installation instructions is actually to create a new dedicated dataset for jailmaker: https://github.com/Jip-Hop/jailmaker#installation so I think that's why this issue wasn't reported yet.

Have fun using your jail :)
