### ISSUE TITLE
is it possible to ssh into the jailed system?

### ISSUE THREAD

**Issue by patrickmichalina** [Jip-Hop/jailmaker#153]
For example, in order to issue remote docker-compose commands or docker-compose contexts for deployments.

**Comment by Jip-Hop** [comment]
It is possible. Please read this section for creating issues:
https://github.com/Jip-Hop/jailmaker?tab=readme-ov-file#filing-issues-and-community-support

**Comment by ad-on-is** [comment]
Just install openssh-server into the jail, and set it's port to 2222 or something else.
