### ISSUE TITLE
Fail to install 

### ISSUE THREAD

**Issue by suchmememanyskill** [Jip-Hop/jailmaker#159]
Hi all,

I've recently built my first NAS and am exploring TrueNAS as an option to run on this machine. I'm running into issues trying to set up docker trough jailmaker. 

![image](https://github.com/Jip-Hop/jailmaker/assets/38142618/37145ac5-57fa-4f26-b4a4-1703714132b5)
![image](https://github.com/Jip-Hop/jailmaker/assets/38142618/4bf0587f-886f-470c-8ea0-894e7f61528f)

Steps to reproduce:
1. Follow [Configure a Dataset for Jailmaker](https://www.truenas.com/docs/scale/scaletutorials/apps/sandboxes/#configure-a-dataset-for-jailmaker) from the official docs
2. Run ./jlmkr.py install
    - This does produce the following warning(?): `Cannot create symlink because /usr/local/sbin/jlmkr is on a readonly filesystem.`
3. Download the docker example config to disk, and run `./jlmkr.py create --start --config /mnt/disk/jailmaker/docker.config dockerjail`

I'm sure i'm just doing something weird here, but i cannot figure out what. Some help would be appriciated. TrueNAS reports no updates are available

**Comment by suchmememanyskill** [comment]
This seems to be caused by not configuring my network adapater properly. What a cryptic error for such a simple configuration mistake. Might also be worth documenting here: https://github.com/Jip-Hop/jailmaker/blob/main/templates/docker/README.md

**Comment by Lockszmith-GH** [comment]
```console
failed to get device eno1: No such device
```

**Comment by suchmememanyskill** [comment]
> failed to get device eno1: No such device

Oh my god i'm actually blind, sorry for the trouble

**Comment by Lockszmith-GH** [comment]
Not blind, more likely, overwhelmed with unnecessary paragraphs.

Personally, I find the `-x` flag of `journalctl` to make things less readable, because of all of the verbiage around the messages.

May I suggest, next time you use **journalctl**, try something like `journalctl -eu jlmkr-dockerjail.service` (without the `-x`), I think its much easier to read.
