### ISSUE TITLE
Jailmaker doesnt work with TrueNAS-SCALE-22.12.3

### ISSUE THREAD

**Issue by muddro1** [Jip-Hop/jailmaker#16]
Jailmaker cant start containers. Already reverted so don't have the specific output. I think it may have to do with this commit, but not sure: https://github.com/truenas/middleware/commit/1d7c9fa0e3f0dec3d71f532d3eb97f5c13cc6695

**Comment by eramdam** [comment]
I got the same issue, here's the log I got

<details>
<pre>
Create a new jail? [Y/n] y

USE THIS SCRIPT AT YOUR OWN RISK!
IT COMES WITHOUT WARRANTY AND IS NOT SUPPORTED BY IXSYSTEMS.

Install the recommended distro (Debian 11)? [Y/n] y

Enter jail name: Scripts

Docker won't be installed by jlmkr.py.
But it can setup the jail with the capabilities required to run docker.
You can turn DOCKER_COMPATIBLE mode on/off post-install.

Make jail docker compatible right now? [y/N] n

Detected the presence of an intel GPU.

Passthrough the intel GPU? [y/N] n

WARNING: CHECK SYNTAX

You may pass additional flags to systemd-nspawn.
With incorrect flags the jail may not start.
It is possible to correct/add/remove flags post-install.

Show the man page for systemd-nspawn? [y/N] n

You may read the systemd-nspawn manual online:
https://manpages.debian.org/bullseye/systemd-container/systemd-nspawn.1.en.html

For example to mount directories inside the jail you may add:
--bind='/mnt/data/a writable directory/' --bind-ro='/mnt/data/a readonly directory/'

Additional flags:

Downloading the image index
Downloading the rootfs
Downloading the metadata
The image cache is now ready
Unpacking the rootfs

---
You just created a Debian bullseye amd64 (20230614_05:24) container.

To enable SSH, run: apt install openssh-server
No default root or user password are set by LXC.

Do you want to start the jail? [Y/n] y
Config loaded!

Starting jail with the following command:

systemd-run --property=KillMode=mixed --property=Type=notify --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=Delegate=yes --property=TasksMax=infinity --collect --setenv=SYSTEMD_NSPAWN_LOCK=0 --unit=jlmkr-Scripts --working-directory=./jails/Scripts '--description=My nspawn jail Scripts [created with jailmaker]' -- systemd-nspawn --keep-unit --quiet --boot --machine=Scripts --directory=rootfs

Starting jail with name: Scripts

Failed to find executable systemd-nspawn: No such file or directory

Failed to start the jail...
In case of a config error, you may fix it with:
nano jails/Scripts/config
</pre>
</details.

**Comment by eramdam** [comment]
Managed to work around it by:

- re-enabling apt and dpkg (`chmod +x /bin/apt*`, `chmod +x /bin/dpkg*`)
- `sudo apt-get update`
- `sudo apt-get install systemd-nspawn`

**Comment by Jip-Hop** [comment]
It looks like the `systemd-container` package was removed since 22.12.3.

Before:

```
apt list --installed | grep -i systemd

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libpam-systemd/now 247.3-7+deb11u1 amd64 [installed,local]
libsystemd0/now 247.3-7+deb11u1 amd64 [installed,local]
libvirt-daemon-system-systemd/now 7.0.0-3 all [installed,local]
python3-systemd/now 234-3+b4 amd64 [installed,local]
systemd-container/now 247.3-7+deb11u1 amd64 [installed,local]
systemd-coredump/now 247.3-7+deb11u1 amd64 [installed,local]
systemd-sysv/now 247.3-7+deb11u1 amd64 [installed,local]
systemd/now 247.3-7+deb11u1 amd64 [installed,local]
```

After:

```
apt list --installed | grep -i systemd

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libpam-systemd/now 252.5-2~bpo11+1 amd64 [installed,local]
libsystemd-shared/now 252.5-2~bpo11+1 amd64 [installed,local]
libsystemd0/now 252.5-2~bpo11+1 amd64 [installed,local]
python3-systemd/now 234-3+b4 amd64 [installed,local]
systemd-coredump/now 252.5-2~bpo11+1 amd64 [installed,local]
systemd-sysv/now 252.5-2~bpo11+1 amd64 [installed,local]
systemd/now 252.5-2~bpo11+1 amd64 [installed,local]
```

So installing `systemd-container` with `apt` will likely make it work again. But jailmaker was nice because it didn't require installing anything...

**Comment by aardvarkl** [comment]
jailmaker is a much better solution that IX's crappy K3S implementation. Maybe not for their target customer (which I am not), but then again I am unconvinced that their target customer is interested in K3S anyway

Not being a Linux expert, is apt install systemd-container or apt install systemd-nspawn the right way to get this back?

**Comment by eramdam** [comment]
> jailmaker is a much better solution that IX's crappy K3S implementation. Maybe not for their target customer (which I am not), but then again I am unconvinced that their target customer is interested in K3S anyway
> 
> Not being a Linux expert, is apt install systemd-container or apt install systemd-nspawn the right way to get this back?

The way I described works. I don't know if it's The Right Way™️ but it does the job 😁

**Comment by Jip-Hop** [comment]
I followed [the three steps](https://github.com/Jip-Hop/jailmaker/issues/16#issuecomment-1592401680) by @eramdam but instead of installing `systemd-nspawn` I installed `systemd-container` and my jail is working again after the upgrade.

So far so good... But too bad systemd-nspawn is no longer included and I'd have to run these commands after each future update.

Will have to see what ix-systems comes up with next to break jails/docker...

**Comment by aardvarkl** [comment]
Just updated Scale to TrueNAS-SCALE-22.12.3.3

"Unable to locate package systemd-nspawn" from sudo apt-get install systemd-nspawn
BUT
sudo apt-get install systemd-container works

**Comment by Jip-Hop** [comment]
Jailmaker does work with version 22.12.3 (confirmed with TrueNAS-SCALE-22.12.3.3), but requires installing the systemd-container package. Jailmaker now comes with an `install` command to help with this: https://github.com/Jip-Hop/jailmaker#install-jailmaker-dependencies

**Comment by florihupf** [comment]
Just here to say this works awesome! Thank you, thank you, thank you!
