### ISSUE TITLE
Adding multiple bridges

### ISSUE THREAD

**Issue by ad-on-is** [Jip-Hop/jailmaker#161]
I need some docker containers to run on a different IP.
In truenas networks, I've got two bridges, br0, and br60 (with vlan60 as member).

I need to pass both br0 and br60 to the jail. Is that possible, or is my thought process wrong?

**Comment by Jip-Hop** [comment]
This is not an issue. Best post this as a discussion on GitHub or in the TrueNAS forum. Jailmaker uses systemd-nspawn under the hood so if it's possible to do this with nspawn you could do it with jailmaker.

Please have a look here: https://github.com/Jip-Hop/jailmaker/discussions/135

In your case I think you may need to create 2 jails, each with a different bridge networking interface or use host networking for your docker jail (but this is not recommended). I only have a single bridge interface so I have no experience with your setup.

I think someone else was trying this in the jailmaker thread on the old TrueNAS forum. You may want to look for those posts.

**Comment by Jip-Hop** [comment]
The best way is probably: https://www.truenas.com/community/threads/linux-jails-experimental-script.106926/post-805938

Please post back or update the docs if you manage to figure this out.

**Comment by ad-on-is** [comment]
Hey... thx for the reply, but I ended up using the host network. It might've probably worked with the bridge only, but I haven't tested that.

So here's what I ended up doing

- Changed TrueNas port from 80/443 to 8000/8043
- Had only a br0 configured in network settings
- Added CAP_NET_ADMIN
- Start jail
- Downgraded Docker to 25.x.x due to issues with ipv6
- Created macvlans docker networks for br0 and br0.XX (vlan tag)
- Done

**Comment by Jip-Hop** [comment]
I think downgrading docker is no longer needed as of the latest version.

**Comment by ad-on-is** [comment]
If they released a version within the last few hours, maybe.

I'm running ricky Linux inside the jail with the centos9 docker repos. They ship docker 26.1.1 (i think), and I had to go way back to 25.0.x to make it work
