### ISSUE TITLE
Feature: edit jail when creating from template

### ISSUE THREAD

**Issue by mrstux** [Jip-Hop/jailmaker#164]
I would like to be able to create a jail from a template, but I’d like to get the edit screen up. 

I don’t want to edit the template before, and I don’t want to have to copy/paste the template into the edit dialog

I guess I could create from template but not start, then edit, then start

but, I have a template which can create a docker jail etc in one go, and just needs the networking adjusted. 

Perhaps a `—edit` flag?

so

`jlmkr create -c templates/docker/config —edit —start docker`

and that should create docker jail called docker, then edit it, then start it. 

This would work well to stream line the current create from template process. 

Or something else, but ideally I’d like to be able to create and edit a jail from a template then start it in one simple step

imagine the tutorial version.

**Comment by Lockszmith-GH** [comment]
@mrstux raises a nice idea.

To your point @Jip-Hop, this means the entire `systemd_nspawn_user_args` will be replaced, and networking is just one switch there.

**Comment by Jip-Hop** [comment]
I appreciate the suggestions! 🙂 

> imagine the tutorial version.

I think it would be more useful to demonstrate the `jlmkr create`, `jlmkr edit` and `jlmkr start` commands in a tutorial as opposed to introducing yet another way to do things.

As you already mention, you can do this currently:

```
jlmkr create --config /path/to/config/template myjail && jlmkr edit myjail && jlmkr start myjail
```

I think this is enough. The `--edit` flag won't be added to the `create` command. Sorry!

**Comment by Lockszmith-GH** [comment]
Sorry to post past closing @Jip-Hop, may I suggest one more alternative, an --append-user_args option to append to whatever is in the config?

An exmaple of usage: With a template sans netwroking, allows invocation with `--append-user_args="--network-bridge=br0"` which will use everything from the template + additonal configuration.

(A followup feature would be to add this flag to `start`, then invocation with additonal flags are possible for a one-time invocation, which is sometimes needed for special setups)

**Comment by mrstux** [comment]
Breaking the process up into "create" then "edit" then "start" is probably a good solution, and is probably what I'll advocate going forwards, if using a template, rather than "copy and paste from github into the create edit dialog with start enabled"

**Comment by Jip-Hop** [comment]
> Sorry to post past closing @Jip-Hop, may I suggest one more alternative, an `--append-user_args` option to append to whatever is in the template?
> 
> An exmaple of usage: With a template sans netwroking, allows invocation with `--append-user_args="--network-bridge=br0"` which will use everything from the template + additonal configuration.
> 
> (A followup feature would be to add this flag to `start`, then invocation with additonal flags are possible for a one-time invocation, which is sometimes needed for special setups)

Sounds interesting. Sounds like a lot of work too. You could create a new feature request. Maybe someone feels like implementing this.
