### ISSUE TITLE
Unable to mount a folder in jails with latest version 1.4.1

### ISSUE THREAD

**Issue by SeiyaGame** [Jip-Hop/jailmaker#174]
**READ THIS FIRST**
[How to ask for help? (including discussion vs issue)](https://github.com/Jip-Hop/jailmaker/discussions/135)

**Describe the bug**
On a clean installation of Truenas scale (24.04.0), I installed the latest version of jailmaker (1.4.1) and the --bind doesn't work. Nothing goes up inside the jail.
I have downgraded the script to version 1.4.0 and all --bind mounts work correctly, but I need to add the fix for the nvidia driver :
`--bind-ro='/usr/lib/x86_64-linux-gnu/nvidia/current'`

**To Reproduce**
1. Install the script in version 1.4.1 and create a new jail with `gpu_passthrough_nvidia=1` and add a --bind mount.
2. Check in the jail if the mount is present, which it isn't.
3. Rollback the script to version 1.4.0 and add `--bind-ro='/usr/lib/x86_64-linux-gnu/nvidia/current'` to fix the error with the nvidia gpu and check if the other --bind mount is present, which it is!

**Expected behavior**
Rollback the https://github.com/Jip-Hop/jailmaker/pull/166 or find an fix

**Comment by Jip-Hop** [comment]
Please try one more time with the latest version and post all the commands used together with all their output. I'm particularly interested in the output which comes after "Starting jail X with the following command:".

**Comment by SeiyaGame** [comment]
I'm completely sorry, version 1.4.1 works very well ...
It's my fault, when I edited the template, I added a comment on the line `systemd_nspawn_user_args` : 
```diff
+systemd_nspawn_user_args=--network-bridge=br1 # My network bridge
    --resolv-conf=bind-host
    --system-call-filter='add_key keyctl bpf'
```

And when I went back to version 1.4.0, I copied and pasted the template on github without adding anything inside, which is why it worked with this version.

I apologize completely for this unnecessary issue I've done ...

_Note to self not to add comments on the same line_
