### ISSUE TITLE
Move jailmaker install location

### ISSUE THREAD

**Issue by LordJuice1** [Jip-Hop/jailmaker#175]
I needed to change my pool name. Long story short, I changed my name that had a space in it, we can call it "test test", to "test_test". Doing that made my existing apps break despite me telling them where to look at. So I had to change it back to "test test". But naturally, when I run `jlmkr list`, it says it cant find /mnt/test_test/jailmaker. Is there an easy way to tell it the new path? And also have it handle a path with a space in it?

**Comment by Lockszmith-GH** [comment]
There should be a way to edit stuff, but until someone who knows how to do that, I'll provide a hack that might work - at least temporarily.

You can try a symbolic link (which might work), or a bind mount which should work.

> ⚠️ NOTE: Both these options here are not permanent in TrueNAS SCALE, as the /mnt folder is part of the boot-pool, which is reset after an upgrade.
> To make them permanent, you'll need to run them everytime the system boots.

A symbolic link:
```console
# ln -s '/mnt/test test' /mnt/test_test
# ls -lahF /mnt

total ...
drwxr-xr-x ## root     root ... ./
drwxr-xr-x ## root     root ... ../
drwxrwxrwx ## apps     apps ... test test/
lrwxrwxrwx ## root     root ... test_test -> '/mnt/test test'
```

A bind mount:
```console
# mkdir /mnt/test_test
# chown apps:apps /mnt/test_test
# mount -o bind '/mnt/test test' /mnt/test_test

# ls -lahF /mnt

total ...
drwxr-xr-x ## root     root ... ./
drwxr-xr-x ## root     root ... ../
drwxrwxrwx ## apps     apps ... test test/
drwxrwxrwx ## apps     apps ... test_test/
```

**Comment by Jip-Hop** [comment]
Which version of SCALE are you using? Are you using the latest version of jailmaker?

**Comment by LordJuice1** [comment]
> Which version of SCALE are you using? Are you using the latest version of jailmaker?

I'm on Dragonfish-24.04.0 and I installed jailmaker yesterday, so I should be

**Comment by Jip-Hop** [comment]
Then you're invoking jailmaker with the shell alias. Check the contents of `/root/.zshrc` and `/root/.bashrc`. You can fix your jailmaker alias in there.

**Comment by LordJuice1** [comment]
I did see the old path in there and made the change from `/mnt/test_test/jailmaker/jlmkr.py` to `/mnt/test\ test/jailmaker/jlmkr.py`. But when I run 'jlmkr list', it still gives the error `zsh: no such file or directory: /mnt/test_test/jailmaker/jlmkr.py`. But I'm respecting a reboot is needed or restart of a service is needed

**Comment by Lockszmith-GH** [comment]
the ...rc files are loaded when you login. if you don't want to re-login, you can just run
```shell
exec $SHELL -l
```
and the envrionment will be reloaded.

**Comment by LordJuice1** [comment]
> the ...rc files are loaded when you login. if you don't want to re-login, you can just run
> 
> ```shell
> exec $SHELL -l
> ```
> 
> and the envrionment will be reloaded.

Thanks for the info!
