### ISSUE TITLE
Unit jlmkr-docker.service could not be found error with ZFS pool that has a space in the name. 

### ISSUE THREAD

**Issue by LordJuice1** [Jip-Hop/jailmaker#177]
**READ THIS FIRST**
[How to ask for help? (including discussion vs issue)](https://github.com/Jip-Hop/jailmaker/discussions/135)

**Describe the bug**
Stupidly, I made my ZFS pool name with a space in the name forever ago. I edited my `/root/.zshrc` and `/root/.bashrc` files as suggested in my previous report (https://github.com/Jip-Hop/jailmaker/issues/175). I can run `jlmkr list` and it'll see my docker install, but running `jlmkr start docker`, does not start it. I figured I'll try installing a new instance(docker1) but get a `Job for jlmkr-docker1.service failed. See "systemctl status jlmkr-docker1.service" and "journalctl -xeu jlmkr-docker1.service" for details.`. Running the systemctl and journalctl gives me

 `Unit jlmkr-docker1.service could not be found.` 

and

 `May 17 22:17:37 thiccfiles (Sas-y)[124280]: jlmkr-docker1.service: Failed to locate executable /mnt/Sas-y: No such file or directory
░░ Subject: Process /mnt/Sas-y could not be executed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The process /mnt/Sas-y could not be executed and failed.
░░ 
░░ The error number returned by this process is ERRNO.
May 17 22:17:37 thiccfiles (Sas-y)[124280]: jlmkr-docker1.service: Failed at step EXEC spawning /mnt/Sas-y: No such file or directory
░░ Subject: Process /mnt/Sas-y could not be executed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The process /mnt/Sas-y could not be executed and failed.
░░ 
░░ The error number returned by this process is ERRNO.
May 17 22:17:37 thiccfiles systemd[1]: Starting jlmkr-docker1.service - My nspawn jail docker1 [created with jailmaker]...
░░ Subject: A start job for unit jlmkr-docker1.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit jlmkr-docker1.service has begun execution.
░░ 
░░ The job identifier is 4973.
May 17 22:17:37 thiccfiles systemd[1]: jlmkr-docker1.service: Control process exited, code=exited, status=203/EXEC
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStartPre= process belonging to unit jlmkr-docker1.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 203.
May 17 22:17:37 thiccfiles systemd[1]: jlmkr-docker1.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit jlmkr-docker1.service has entered the 'failed' state with result 'exit-code'.
May 17 22:17:37 thiccfiles systemd[1]: Failed to start jlmkr-docker1.service - My nspawn jail docker1 [created with jailmaker].
░░ Subject: A start job for unit jlmkr-docker1.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit jlmkr-docker1.service has finished with a failure.
░░ 
░░ The job identifier is 4973 and the job result is failed.`

I dug into `/lib/systemd/system/` but I don't see anything referring to docker.

How do I make it handle my pool having the space in the name? Should I remove jlmkr and start fresh? Is there more files to edit? I don't have anything set up so there is no heart break starting over

**To Reproduce**
1. Put a space in your pool name like a fool
2. 
3. See error

**Expected behavior**
Docker service to run

**Screenshots**

**Jailmaker:**
 - Version 1.4.1

**TrueNAS SCALE:**
 - Version 24.04.0

**Additional context**

**Comment by Jip-Hop** [comment]
What is the full path to jailmaker (e.g. /mnt/your pool/jailmaker)?

Please post the config files of both of your docker jails (you can see it with jlmkr edit or look in the jails/docker directory).

The log you've posted indicates there's an error executing the pre start hook: 

```
An ExecStartPre= process belonging to unit jlmkr-docker1.service has exited
```

**Comment by Jip-Hop** [comment]
Also please post all output of `jlmkr start docker1`. I'm particularly interested in the output which comes after "Starting jail X with the following command:".

**Comment by LordJuice1** [comment]
The full path is /mnt/Sas-y data/jailmaker. I attached both of the config files
[jlmkr docker.txt](https://github.com/Jip-Hop/jailmaker/files/15367000/jlmkr.docker.txt)
[jlmkr docker1.txt](https://github.com/Jip-Hop/jailmaker/files/15367001/jlmkr.docker1.txt).

Running `jlmkr start docker1` (and `docker`) result in this output

````
Starting jail docker1 with the following command:

systemd-run --property=KillMode=mixed --property=Type=notify --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=Delegate=yes --property=TasksMax=infinity --collect --setenv=SYSTEMD_NSPAWN_LOCK=0 --unit=jlmkr-docker1 --working-directory=./jails/docker1 '--description=My nspawn jail docker1 [created with jailmaker]' '--property=ExecStartPre=/mnt/Sas-y data/jailmaker/jails/docker1/.ExecStartPre' -- systemd-nspawn --keep-unit --quiet --boot --bind-ro=/sys/module --inaccessible=/sys/module/apparmor --machine=docker1 --directory=rootfs --bind=/dev/nvidiactl --bind-ro=/usr/bin/nvidia-persistenced --bind-ro=/usr/lib/nvidia/current/nvidia-smi --bind=/dev/nvidia-uvm --bind=/dev/nvidia-modeset --bind-ro=/usr/bin/nvidia-smi --bind=/dev/nvidia0 --bind=/dev/nvidia-uvm-tools --bind-ro=/usr/lib/x86_64-linux-gnu/nvidia/current --notify-ready=yes --network-bridge=br0 --resolv-conf=bind-host '--system-call-filter=add_key keyctl bpf' '--bind=/mnt/Sas-y\ data/docker/data:/mnt/data' '--bind=/mnt/Sas-y\ data/docker/stacks:/opt/stacks'

Job for jlmkr-docker1.service failed.
See "systemctl status jlmkr-docker1.service" and "journalctl -xeu jlmkr-docker1.service" for details.

Failed to start jail docker1...
In case of a config error, you may fix it with:
jlmkr edit docker1
````

**Comment by LordJuice1** [comment]
I don't know if it helps any, but here is a screenshot of the app pool. `docker` is what i started with. `docker1` is what i made as a test
![image](https://github.com/Jip-Hop/jailmaker/assets/140874565/5d6a36ab-88c3-43cc-96a0-c414a9e7d171)

**Comment by Jip-Hop** [comment]
I suppose the bug is that `'--property=ExecStartPre=/mnt/Sas-y data/jailmaker/jails/docker1/.ExecStartPre'` is not properly quoted.

For now I think you can make it work by removing the pre start hook from your config. You'll need to run the commands from the pre start hook manually before running your jail.

The next release of jailmaker should fix this bug.

**Comment by LordJuice1** [comment]
Could I edit that value at all so it would be quoted correctly? If so, where would I do that?

The only thing I see in the config file about pre start is 

> ```
> # Script to run on the HOST before starting the jail
> # Load kernel module and config kernel settings required for docker
> pre_start_hook=#!/usr/bin/bash
> 	set -euo pipefail
> 	echo 'PRE_START_HOOK'
> 	echo 1 > /proc/sys/net/ipv4/ip_forward
> 	modprobe br_netfilter
> 	echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
> 	echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
> ```

**Comment by Jip-Hop** [comment]
No sorry it needs to be fixed in jailmaker itself. You could remove the whole pre_start_hook section. Or rename your zfs pool:
https://forums.truenas.com/t/howto-rename-a-zfs-pool/130

**Comment by LordJuice1** [comment]
I can wait until the next release of jailmaker

**Comment by Jip-Hop** [comment]
Should be fixed now in the latest release.

**Comment by LordJuice1** [comment]
I can confirm that it is working now. Thanks!

**Comment by major-mayer** [comment]
I guess jails with a dash in their name fall into the same category of not being properly quoted?

```
jlmkr start docker-jail

Starting jail docker-jail with the following command:

systemd-run --property=KillMode=mixed --property=Type=notify --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=Delegate=yes --property=TasksMax=infinity --collect --setenv=SYSTEMD_NSPAWN_LOCK=0 --unit=jlmkr-docker-jail --working-directory=./jails/docker-jail '--description=My nspawn jail docker-jail [created with jailmaker]' --property=ExecStartPre=/mnt/data/jailmaker/jails/docker-jail/.ExecStartPre -- systemd-nspawn --keep-unit --quiet --boot --bind-ro=/sys/module --inaccessible=/sys/module/apparmor --machine=docker-jail --directory=rootfs --bind=/dev/dri --notify-ready=yes --network-bridge=br1 --resolv-conf=bind-host '--system-call-filter=add_key keyctl bpf'

Job for jlmkr-docker-jail.service failed.
See "systemctl status jlmkr-docker-jail.service" and "journalctl -xeu jlmkr-docker-jail.service" for details.

Failed to start jail docker-jail...
In case of a config error, you may fix it with:
jlmkr.py edit docker-jail
```
