### ISSUE TITLE
What starts the last run docker compose when bringing up a jail?

### ISSUE THREAD

**Issue by florihupf** [Jip-Hop/jailmaker#18]
Hi there,

I just rebooted Scale and found that starting a jail also brings up the last run docker compose.

How does that work?

I expected to manually need to run docker compose up ... 

Do I miss something?

**Comment by Jip-Hop** [comment]
That's normal docker behavior. If you don't want those containers to start up again you'd need to run `docker compose down` from the directory of your compose file. Or perhaps you want to use a different restart policy: https://docs.docker.com/config/containers/start-containers-automatically/

The 'jail' goes trough the regular init process and starts all enabled services.
