### ISSUE TITLE
[Feature Request] change jlmkr default action with no args

### ISSUE THREAD

**Issue by Lockszmith-GH** [Jip-Hop/jailmaker#184]
When running jlmkr without any argument, the default is creating a new jail (I think this [is the spot](https://github.com/Jip-Hop/jailmaker/blob/d2eeefcf8ed45833acb51541528e88d39ddadc68/jlmkr.py#L2153)).
While it is a very important step, it is the one action that will probably be the least useful to run after initial setup.

Would it make more sense that the help output show? similar to `git`, `docker`, `kubectl`, etc... ?
If you would rather it be useful, maybe the `list` sub-command then?

**Comment by Jip-Hop** [comment]
Well it prints the help message if you answer no. So it kind of does both currently. Create or help. I think this makes it as easy as possible to get started right from the terminal if you don't have the docs in front of you.

**Comment by Lockszmith-GH** [comment]
Probably just me nitpicking - closing FR.
