### ISSUE TITLE
Add an option to stop all jails at once

### ISSUE THREAD

**Issue by UnderEu** [Jip-Hop/jailmaker#192]
**READ THIS FIRST**
[How to ask for help? (including discussion vs issue)](https://github.com/Jip-Hop/jailmaker/discussions/135)

**Is your feature request related to a problem? Please describe.**
No, at least not directly

**Describe the solution you'd like**
I'd like the script to add an option to stop all jails at once. In case I need to grace shutdown my host system due to a power outage or for applying an OS update, for example, I can safely shutdown all jails and then do the thing on the host OS itself.
Not sure if that already happens but I'd be nice to have the option to do so.

**Describe alternatives you've considered**
Currently, I manually stop all my jails one by one, by using the `jlmkr stop foo` command. My current list is fairly small (< 10) but for larger deployments (I saw one guy with almost 60 jails deployed, one time), this could be troublesome.

**Additional context**
N/A

**Comment by Jip-Hop** [comment]
Shut down is already gracefull when you shutdown or reboot the host normally. But I agree it could be useful to be able to shutdown all jails with one command.

**Comment by mrstux** [comment]
jlmkr startup will start all jails that have startup=1... maybe `jlmkr shutdown` would be useful?

And then startup could be used to restore?

**Comment by marshalleq** [comment]
Came here because I think jailmaker if holding files open preventing me from deleting a snapshot.  I am looking for a way to shut down jailmaker without having to delete / disable the startup script and reboot.  So I would agree that a shutdown option would be useful.

**Comment by Jip-Hop** [comment]
Closing as not planned due to [End of Life October 2024 Announcement](https://github.com/Jip-Hop/jailmaker/discussions/241).
