### ISSUE TITLE
Talos OS

### ISSUE THREAD

**Issue by ac1dburnz** [Jip-Hop/jailmaker#195]
Would love to get Talos os as an option

**Comment by Jip-Hop** [comment]
Incompatible.

> There is no systemd on our system.

https://www.talos.dev/v1.2/learn-more/concepts/

**Comment by Jip-Hop** [comment]
But you can run Talos with docker inside a jail: https://www.talos.dev/v1.7/talos-guides/install/local-platforms/docker/.
