### ISSUE TITLE
No IP inside jail

### ISSUE THREAD

**Issue by x-cimo** [Jip-Hop/jailmaker#196]
Hello!

My docker jail dosen't get an IP and interface show as down, can you spot anything wrong? Thanks!

`
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever

2: mv-enp15s0f1@if4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 72:5b:20:98:b7:f9 brd ff:ff:ff:ff:ff:ff link-netnsid 0

3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:c1:b8:49:8e brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
`

The interface from the host:
`enp15s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 90:e2:ba:5a:6f:5d brd ff:ff:ff:ff:ff:ff
    inet 10.100.1.10/16 brd 10.100.255.255 scope global enp15s0f1`

I've set the following inside the jail
`
[Match]
Virtualization=container
Name=mv-*

[Network]
DHCP=false
Address=10.100.1.11/16 
Gateway=10.100.0.1
`

And finally here is my config:
`
systemd_nspawn_user_args=--network-macvlan=enp15s0f1
        --resolv-conf=bind-host
        --system-call-filter='add_key keyctl bpf'
        --private-users=65536:65536
        --private-users-ownership=chown
`

**Comment by Jip-Hop** [comment]
I don't immediately see anything wrong. Did it work before you modified the network config file? By default the macvlan interface will get the IP address via DHCP.

**Comment by x-cimo** [comment]
yes before I edit the file docker install and networking is working

`2: mv-enp15s0f1@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 72:5b:20:98:b7:f9 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.100.5.113/16 metric 1024 brd 10.100.255.255 scope global dynamic mv-enp15s0f1
       valid_lft 7167sec preferred_lft 7167sec
    inet6 fd7d:bfb9:a81d:fa1d:705b:20ff:fe98:b7f9/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 1769sec preferred_lft 1769sec
    inet6 fe80::705b:20ff:fe98:b7f9/64 scope link
       valid_lft forever preferred_lft forever
`

Then I edit /etc/systemd/network/mv-dhcp.network

`[Match]
Virtualization=container
Name=mv-*

[Network]
#DHCP=yes
#LinkLocalAddressing=ipv6
DHCP=false
Address=10.100.1.11/16
Gateway=10.100.0.1


#[DHCPv4]
#UseDNS=true
#UseTimezone=true
`

reboot and no more network

**Comment by Jip-Hop** [comment]
I don't know what is going wrong but I'm sure this is not a jailmaker bug. Alternatively you can make a static lease in your dhcp server (router).

**Comment by x-cimo** [comment]
one thing I found out is regardless if I make a static ip or not, the DHCP only work the first time.  If run the initial config, dhcp is up, if I reboot it, the IP is gone and wont renew.

**Comment by Jip-Hop** [comment]
Did you check if the mv-dhcp.network file has the correct ownership/permissions after creating/modifying it in relation to user remapping? Otherwise I have no clue.

**Comment by x-cimo** [comment]
You are right. I didin't know permission had to be modified on rootfs on the hosts.

Theses automate this process for newbies like me:
--private-users=pick
--private-users-ownership=chown

Thanks @Jip-Hop
