### ISSUE TITLE
Ip address checks

### ISSUE THREAD

**Issue by ac1dburnz** [Jip-Hop/jailmaker#206]
**READ THIS FIRST**
[How to ask for help? (including discussion vs issue)](https://github.com/Jip-Hop/jailmaker/discussions/135)

**Is your feature request related to a problem? Please describe.**
when you have multiple jails and apps there should be a check to make sure there are no duplicate ips. I was able to manually assign the same ip to two different jails 

**Describe the solution you'd like**
create a validation to ensure only one ip is being used at one time. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Jip-Hop** [comment]
How did you assign those IP addresses? I think this is out of scope for jailmaker. It's the same with VMs on a bridge, or any device on your LAN really. You can manually assign the same IP address to any of those systems and mess things up.
