### ISSUE TITLE
Feature Request: Accepting config template from stdin

### ISSUE THREAD

**Issue by Lockszmith-GH** [Jip-Hop/jailmaker#208]
```bash
jlmkr create --start --config <template file path> <jail-name>
```

is such a great feature, I would recommend exapding it to allow input form stdin, which would allow something like:

```bash
jlmkr create --start --config - nixos < <( curl -sL https://raw.githubusercontent.com/Jip-Hop/jailmaker/develop/templates/nixos/config )
```

or even:
```bash
jlmkr create --start --config - nixos < <( curl -sL https://raw.githubusercontent.com/Jip-Hop/jailmaker/develop/templates/nixos/config | sed -e 's|/br1|/br0|')
```

The common convetion in linux is to read from stdin when a dash (`-`) is passed a file name, so following that seems like a safe option.

**Comment by Jip-Hop** [comment]
Try it like this:

```
jlmkr create --start --config=<( curl -sL https://raw.githubusercontent.com/Jip-Hop/jailmaker/develop/templates/nixos/config) nixos
```

**Comment by Lockszmith-GH** [comment]
Yes, I thought of that, this will work if I'm in a root login (yes, yes, I know - I should be in it already), but if runing via sudo, the file-descriptor does not pass across the different contexts. The pipeline does not have this limitation.

```console
$ sudo jlmkr create --start --config <(cat $SCALE_POOL_ROOT/jailmaker/templates/nixos/config) nixostest
USE THIS SCRIPT AT YOUR OWN RISK!
IT COMES WITHOUT WARRANTY AND IS NOT SUPPORTED BY IXSYSTEMS.
Creating jail nixostest from config template /dev/fd/63.
Failed to read config template /dev/fd/63.

```

**Comment by Jip-Hop** [comment]
Yes, I see. PR is welcome if you feel like implementing this! 😉 [The config file handling needs a bugfix too](https://github.com/Jip-Hop/jailmaker/issues/209).

**Comment by Lockszmith-GH** [comment]
I'll take a look later today, felx my Python a bit :)

**Comment by Jip-Hop** [comment]
This should now work with jlmkr on the develop branch.

```bash
curl -sL https://raw.githubusercontent.com/Jip-Hop/jailmaker/develop/templates/docker/config | jlmkr create --start --config - docker
```

Please test and provide feedback.

**Comment by Lockszmith-GH** [comment]
I did, and I love it
