### ISSUE TITLE
Enhancing/validating config templates

### ISSUE THREAD

**Issue by jonct** [Jip-Hop/jailmaker#228]
I just finished [saying](https://github.com/Jip-Hop/jailmaker/issues/221#issuecomment-2216370920) that nobody needs some newcomer to second-guess how Jailmaker is organized. So, uh… sorry. 😶‍🌫️ This one's kind of disruptive.

### Summary

Might it still be reasonable to suggest adopting YAML-based templates?

### Background

The current template format is clever and not hard to learn, but it brings some surprises. Among them:

- Comments must begin at the first column, even within indented content.
- Some multiline blocks collapse into space-delimited options; others into newline-delimited scripts.
- Rules for escaping border on trial-and-error.
- Lack of variable substitution makes structure and self-documentation tricky.
- Overall it could be made clearer where syntax ends and conventions take over.
- There's even a dynamically generated regex in the implementation that makes me squeamish.

### Proposal

iX has preinstalled `PyYAML` for use by its middleware; it's unlikely to ever disappear. It could solve all of the above† quickly, and together.

- Leveraging a well-known, rigorously defined standard.
- Engaging editor support for syntax coloring and validation.
  - *Especially for script blocks!*
- Validating both syntax and semantic content of PRs.
- Validating both syntax and semantic content for CLI invocations.
- Reducing code maintenance.

† It wouldn't do anything for variable interpolation, unfortunately. But there are conventions and unit testable starting points.

### Alternatives considered

It would be easy to call for new documentation PRs. And for more eyes on the code. And for a robust suite of parser unit tests (hat tip to @Lockszmith-GH!) And for additional code to validate syntax and emit smart warnings and errors in actionable context…

I was initially only going to ask about enabling `ExtendedInterpolation` in the `KeyValueParser`. Just so that basic user-specified params (interface names, IP addresses, host paths…) could be grouped and documented at the top of a template.

But while digging in the weeds on interpolation, it occurred to me that the file structure doesn't derive from any waypoints in the `systemd-nspawn` world. It's just an entirely bespoke file format in apparent need of testing, tooling, and documentation.

### Next steps

If I were to write a config migration function into `jlmkr.py`, would you consider the leap?

**Comment by Jip-Hop** [comment]
I was so happy the jlmkr.py script didn't rely on any external Python packages. 🥲 But I was also sad Python lacks built-in support for YAML. So I'd be open to migration to YAML. But I'd still prefer to minimize external dependencies (even if they are currently shipped with SCALE). Perhaps this pattern could help to still run jlmkr.py without first manually installing the Python dependencies: https://gist.github.com/Jip-Hop/15aa2b9bf9134242ad00bac5f021bc7c

But how does YAML handle comments? Preserving comments in the templates (even when some value is overridden) helps the user understand how to edit the config.

**Comment by Jip-Hop** [comment]
Sure! But also keep in mind that iX has plans to incorporate/copy/adopt jailmaker functionality and/or code into their own codebase. If/when this happens I can imagine the config format would be evaluated, and perhaps changed. Maybe that would be the right moment to migrate to YAML and of course iX can then use PyYAML and any other Python packages they desire to implement what I tried to do with minimal dependencies...

**Comment by Jip-Hop** [comment]
I'm open to exploration and I truly appreciate the interest and suggestions, newcomer or not. In my opinion what jailmaker needs right now is an extensive test suite (integration tests as well as python unit tests). I realize using well tested (external) libraries could contribute to this to some degree...

I'm really glad Lockszmith-GH has started working on #86 as it's becoming increasingly difficult [to fix one thing](https://github.com/Jip-Hop/jailmaker/pull/219/commits/762b83a8c82621bd952ff8079a000ae3a7180f1e) [without breaking something else](https://github.com/Jip-Hop/jailmaker/actions/runs/9849925535). So instead of disruptive changes or new features I hope automated testing of jailmaker will take flight! How is your python and are you interested in helping out?

**Comment by Jip-Hop** [comment]
> I take from iX's intentionally separate "sandboxes" branding that they foresee a different overview.

AFAIK iX is not planning anything drastically different from jailmaker. [According to Kris from iX](https://forums.truenas.com/t/add-nodes-to-truenas-scale-kubernetes-cluster-and-another-doubt/1703/4):

> Jailmaker is a nice tool. We figure its only time before we do a proper UI-based “sandboxes/jails” system in SCALE and when we do that we’d expect it to carry forward any current jailmaker managed environments fairly easily.

Glad to hear you want to help out :) Looking forward to your proposal!

**Comment by Jip-Hop** [comment]
> So there haven't been any significant backchannel communications with iX?

There has been some. But it's probably too early to say for sure how they're going to address it.

**Comment by Jip-Hop** [comment]
Closing as not planned due to [End of Life October 2024 Announcement](https://github.com/Jip-Hop/jailmaker/discussions/241).
