### ISSUE TITLE
Fallback to default config

### ISSUE THREAD

**Issue by Jip-Hop** [Jip-Hop/jailmaker#229]
When providing an incomplete config file, fallback to the default config for the missing values and write the interpolated config file.

Currently this works:

```
jlmkr create --start --config=- test <<END
initial_setup=apt-get update
    apt-get install -y curl
distro=debian
release=bookworm
END
```

But the resulting config file is very minimal:

```
initial_setup=apt-get update
        apt-get install -y curl
distro=debian
release=bookworm
systemd_nspawn_user_args=
```

And this doesn't work (because `image` and `distro` don't fallback to defaults during `jlmkr create`:

```
jlmkr create --start --config=- test <<END
initial_setup=apt-get update
    apt-get install -y curl
END
```

However keep in mind that comments should be preserved when the user provides a complete (or almost complete?) config file. In that case we don't want to take the default config (with comments) as the base.

**Comment by Lockszmith-GH** [comment]
Like it very much - best to surround additions with a BEGIN/END comment

**Comment by Jip-Hop** [comment]
What do you mean? If it's the `END` tags then I'm afraid it's not possible to use a different tag for `BEGIN` and `END` as this is [heredoc syntax](https://www.geeksforgeeks.org/how-to-use-heredoc-in-shell-scripting/). But I agree it's probably better to use another delimiter than `END` but that's up to the user anyway.

**Comment by Jip-Hop** [comment]
Hmm that's one option for sure. But I think I rather have something more complete like the default config at the top of jlmkr.py

https://github.com/Jip-Hop/jailmaker/blob/c1f6990b7fca6e2e7e93eca645d3e9b9e141f3e6/jlmkr.py#L37-L101

**Comment by Lockszmith-GH** [comment]
I see... interesting. Not against - just never seen it like that.
