### ISSUE TITLE
jlmkr-test FR: produce journald output after a failed test step

### ISSUE THREAD

**Issue by Lockszmith-GH** [Jip-Hop/jailmaker#230]
When a test fails, sometimes stdout and stderr don't contain enough information to identify the cause of the failure.

If a step fails, journald should contain more detail.

Something like:

```console
# jlmkr log docker | cat -
```

@Jip-Hop, I'll wait for your approval on this before I tackle it.

**Comment by Lockszmith-GH** [comment]
Related Links
Issue #86, PR #215 
PR #219 failures introduced by [this commit](https://github.com/Jip-Hop/jailmaker/pull/219/commits/762b83a8c82621bd952ff8079a000ae3a7180f1e)

**Comment by Jip-Hop** [comment]
Looks like a good idea! Go for it :D
