### ISSUE TITLE
This script should be owned by the root user...

### ISSUE THREAD

**Issue by Kieros** [Jip-Hop/jailmaker#25]
Eager to try this out but I am logged in as root, created the dataset followed the first steps.
And I get stuck here 

![image](https://github.com/Jip-Hop/jailmaker/assets/99768682/2e79de2b-0994-4977-abce-69bb68911a73)

Als tried sudo what am I doing wrong?

**Comment by Kieros** [comment]
Sorry I think I missed to run it as post init :S

**Comment by Jip-Hop** [comment]
What is the output of `ls -la` inside the folder where you stored jlmkr.py?

**Comment by Kieros** [comment]
![Screenshot_20230814_010458_Chrome](https://github.com/Jip-Hop/jailmaker/assets/99768682/17d02430-7826-40cf-9335-28e80512190f)

**Comment by Jip-Hop** [comment]
As you can see the file is not owned by root but by Gerard instead. Don't know how you did that but you can fix it with `chown root jlmkr.py` as root user.

**Comment by Kieros** [comment]
I think that is the root user the real root was disabled. 
So with that user I downloaded the file.

**Comment by Kieros** [comment]
I will try this

**Comment by Kieros** [comment]
Allright that did it.Thank you for the quick response. 
Installed with succes
