### ISSUE TITLE
Can I adding Coral TPU (NVMe/PCIe) to jails?

### ISSUE THREAD

**Issue by abe520** [Jip-Hop/jailmaker#251]
Can I bind it?
https://github.com/blakeblackshear/frigate/discussions/9457
```
lspci -nn | grep 089a
01:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
```

**Comment by dalgibbard** [comment]
@abe520 I have one on my system, you have to edit the jail to include:
```'--property=DeviceAllow=char-usb_device rwm'```
```'--property=DeviceAllow=/dev/ttyUSB0 rwm'``` 
```--property=DeviceAllow=/dev/bus/usb```
```--bind=/dev/bus/usb```
``` --bind=/dev/ttyUSB0```

Not sure if all are needed etc; so play around with that I guess, but is working for me
