### ISSUE TITLE
Mounting external devices

### ISSUE THREAD

**Issue by DavidePgr** [Jip-Hop/jailmaker#254]
**READ THIS FIRST**
[How to ask for help? (including discussion vs issue)](https://github.com/Jip-Hop/jailmaker/discussions/135)

**Is your feature request related to a problem? Please describe.**
I tried mounting an external device to create a "dumping station" on the jail I created, and while the OS (Debian 12) recognize the external SD, it does not let me mount it to a folder with the `mount` command, since the device is not present in the `/dev` directory.

**Describe the solution you'd like**
A way to pass through the external device from TrueNAS Scale to the jail.

**Describe alternatives you've considered**
I tried mounting the external device from the TrueNAS Scale shell, bui it creates some wierd errors.

**Additional context**
I installed TrueNAS Scale 24.04.2 directly on a Ugreen 6800 Pro NAS, and I am managing apps with docker containers on a jailmaker Debian 12 jail. I'd like to use the NAS I/O (SD card reader, Thunderbolt/USB-C ports, etc...) to dump files directly on a TrueNAS Scale share; to do that I was planning to use jailmaker to mount the external device and copy the files on a directory binded to a share. Any suggestion/improvement to my idea is very welcome! Thanks

**Comment by Lockszmith-GH** [comment]
I'm not sure mounting from within the jail is the right strategy here, it's probably mounting into TrueNAS SCALE, and then binding into the jail. But you wrote that that failed as well.

Please share the commands you have attempted, with the errors.
Please share details about the hardware of the mount.

If you can't mount it on TrueNAS SCALE, you probably won't be able to mount it within the jail, so I suggest focusing your effort on mounting to the host first.

**Comment by DavidePgr** [comment]
It didn't work beacuse I tried mounting it directly into a zfs directory🤦‍♂️ now I tried mounting it inside the /media linux directory and it works, and by binding that to the jail I can copy files from there to any zfs directory. Problem solved, thanks!
