### ISSUE TITLE
Delete jails

### ISSUE THREAD

**Issue by Ixian** [Jip-Hop/jailmaker#3]
Feature request: Would be nice to have an option to delete or otherwise clean up jails created by the script rather than having to do it manually. Something like "./jlmkr.py remove myjail" with a confirmation prompt ("Are you sure Y/n")

**Comment by qudiqudi** [comment]
👍

**Comment by qudiqudi** [comment]
Correct me if I'm wrong @Jip-Hop but deleting a jail is nothing more than removing the specific folder named after that jail, right?

**Comment by Jip-Hop** [comment]
That is correct, it is as simple as that! But a remove command in `jlmkr.py` could be useful. To prompt for confirmation, and also to stop the jail (in case it was running) before removing the folder.

**Comment by Jip-Hop** [comment]
Thanks to @qudiqudi and his friend this is now available.
