### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by Kieros** [Jip-Hop/jailmaker#30]
./jlmkr.py install
systemd-nspawn is already installed.
File /usr/local/sbin/jlmkr already exists... Maybe it's a broken symlink from a previous install attempt?
Skipped creating new symlink /usr/local/sbin/jlmkr to /mnt/SSD1/jailmaker/jlmkr.py.
Done installing jailmaker.

How do I fix this?
I had to rename the zpool because it was ridiculously long. But now I can not use the jlmkr command nor can I reïnstall it?

**Comment by Jip-Hop** [comment]
You can remove this file: `/usr/local/sbin/jlmkr`
