### ISSUE TITLE
Cant start ~ 10 jails. Too many open files

### ISSUE THREAD

**Issue by spusuf** [Jip-Hop/jailmaker#31]
If you run `jlmkr start jailname` it wont throw an error but running `jlmkr list` will show the jail is not running. Machinectl confirms it is not running. The `journalctl` error is `Too many open files`.

**Comment by spusuf** [comment]
As suggested in the systemd git page, setting `sysctl fs.inotify.max_user_watches=16384` fixed temporarily but is ignored on reboot. Can confirm current and previous settings by running `cat /proc/sys/fs/inotify/max_user_watches`.

Could also be the fs settings in `sysctl --all`. Will have to test further.

**Comment by Lockszmith-GH** [comment]
There are several discussion about this online ([here](https://www.truenas.com/community/threads/scale-syncthing-inotify-limits.102919/#post-708149) is just one I found)

Setup the value that makes sense to your system via the UI at:
>  System Settings -> Advanced -> Sysctl

**Comment by spusuf** [comment]
> There are several discussion about this online ([here](https://www.truenas.com/community/threads/scale-syncthing-inotify-limits.102919/#post-708149) is just one I found)
> 
> Setup the value that makes sense to your system via the UI at:
> 
> > System Settings -> Advanced -> Sysctl

Ah you legend. I thought it was a systemd-nspawn + Linux issue, but it completely makes sense that it's a TrueNAS issue and I didn't think to search for that. 

Do you know what changing that value affects and if there's any downsides (or reasons the TrueNAS team would have done that)? Also what's the optimal value, just copy the TrueCharts value?

**Comment by Lockszmith-GH** [comment]
Well, as any sysctl setting, there are pros and cons, but with TrueNAS SCALE, especially with the k3s system installed and active on it, there is so much going on that the defaults just don't make sense.

I can share what I did on my system:
- Intel(R) Xeon(R) CPU X5460 @ 3.16GHz (8 cores)
- RAM (ECC): 32GiB
- Storage Pool A: 1 x RAIDZ2 | 5 wide | 9.1 TiB
- Storage Pool B: 1 x MIRROR | 2 wide | 12.73 TiB

My sysctl settings are:
- fs.inotify.max_user_instances = 1024
- fs.inotify.max_user_watches = 12288

I currently don't run any Jails (nor VMs, this CPU is way too old for that) on this system, but I do run ~20+ ix-apps.

**Comment by Jip-Hop** [comment]
Thanks for helping @Lockszmith-GH 👍
