### ISSUE TITLE
Usb passthrough 

### ISSUE THREAD

**Issue by Kieros** [Jip-Hop/jailmaker#33]
Maybe I missed it during setup. But also not sure where to post this question as perhaps this is no issue. 

How do I get "dev/serial/by-id/someusb" from truenas scale into the jail? Can I just add a --bind-ro to this folder?
Or is that not accesible as it is not a mount folder?
I'd like to add zwave stick as a device to zwave-js-ui container. I don't see this dev folder in the jail

**Comment by Jip-Hop** [comment]
I'd say try some stuff out! And otherwise there's always the systemd-nspawn manual :D

**Comment by Kieros** [comment]
Sofar I tried to bind the /dev/serial/by-i/usbdevice but somehow it looks okay and it is in the jail but the container is not accepting it as a serial usb device. I don't see any other usefull stuff in the systemd-nspawn manual.

**Comment by Jip-Hop** [comment]
Did you only try --bind-ro or also a regular --bind? The only device I've ever mounted person all is the Intel GPU /dev/dri. So don't have experience with this bit.

**Comment by Jip-Hop** [comment]
Perhaps try this: https://unix.stackexchange.com/questions/304252/access-usb-device-from-systemd-nspawn-container

**Comment by Kieros** [comment]
I have tried both mounts. I also copied the /dev/serial/by-id/ folder to the rootfs folder of the debian jail and restarted the debian jail. I can see the serial device in the jail in the dev folder. But same problems with the -bind method.
It looks like it is not recognized as a real device.

**Comment by Kieros** [comment]
whoa that link you gave is like rocket science to me newbie linux user :)

**Comment by Kieros** [comment]
Well I am pretty stuck with this and it is a big dissapointment that it is this difficult to only get a usb device passed through to the jail. I actually thought that this would not be a problem as it has been arround for so long.

Thus I think this is not the way. Too bad because everything is running fine sofar in the bookworm jail. But I am out of ideas. 
I also tried the --console=modes setting in systemd-nspanwn copied the dev folder etc. But I do not fully understand some linux concepts. So I have been reading and try for many hours these days to no avail. 
As mentioned before, how hard would it be to give the jail some access to the hosts connected usb or some devices?

I hope you have any idea left on how to do this or I should be going back to the launch docker image thing or some lightweight vm to run docker on. At least there I was able to passthrough the usb.

**Comment by Jip-Hop** [comment]
I think you are the first person to try this with jailmaker.

In general it is recommended to post the steps you have taken and the output, logging, screenshots etc. if you're posting an issue or asking for help as otherwise I can only guess.

What you can do is post the output of of the `jlmkr start nameofyourjail`. It should show you the `systemd-run` command that's being used to start the jail.

I don't think copying the dev directory is going to help. But you should definitely add the path to the usb device with the `--bind` option. Then the second thing that seems to be needed, according to the link I found and posted, is to add: `--property=DeviceAllow=char-usb_device rwm`. I don't think char-usb_device is meant literally though. I guess you need to replace it with the name/identifier of that device on your system.

So try to experiment a bit with those two options and read the link again. Maybe it will make more sense now. Good luck!

**Comment by Kieros** [comment]
thanks I will try that

**Comment by Kieros** [comment]
this is the output 
Starting jail debian with the following command:

systemd-run --property=KillMode=mixed --property=Type=notify --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=Delegate=yes --property=TasksMax=infinity --collect --setenv=SYSTEMD_NSPAWN_LOCK=0 --unit=jlmkr-debian --working-directory=./jails/debian '--description=My nspawn jail debian [created with jailmaker]' --setenv=SYSTEMD_SECCOMP=0 --property=DevicePolicy=auto -- systemd-nspawn --keep-unit --quiet --boot --machine=debian --directory=rootfs --capability=all '--system-call-filter=add_key keyctl bpf' --bind=/mnt/SSD1/opt --console=interactive

Running as unit: jlmkr-debian.service

**Comment by Kieros** [comment]
Nowa!y that I didn't think of this before :)
I tried before to bind it with the serial by-id path, but had not tried to just mount the ttyACM0 which is the device.
I figured why not try this instead I have never seen it change during boot up etc. it has always been ttyACM0

I was mislead with the zwave-js-ui docker-compose file to go with the serial by id. 
 devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.

I just had to use --bind='/dev/ttyACM0' and ad this to zwave-js-ui

 zwave-js-ui:
    container_name: 'zwave-js-ui'
    image: 'zwavejs/zwave-js-ui:latest'
    restart: 'unless-stopped'
    tty: true
    environment:
      - 'TZ=Europe/Amsterdam'
    devices:
      - '/dev/ttyACM0'
    volumes:
      - type: 'bind'
        source: '/mnt/SSD1/opt/zwave-js-ui'
        target: '/usr/src/app/store'
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server

**Comment by victor-perez** [comment]
BTW, I did get it working by `--bind /dev/serial/by-id/X` ( not `--bind-ro` ) and then for docker-compose:
```yml
devices:
 - /dev/serial/by-id/X:/dev/ttyUSB0
 ```
