### ISSUE TITLE
Bridge interface behaving badly

### ISSUE THREAD

**Issue by aardvarkl** [Jip-Hop/jailmaker#36]
I have a TrueNAS Scale - on the latest release (Bluefin) version and have been using jailmaker as a test for a while.
I have a single jail running portainer

When the jail is not running I do not have the issue shown here - but when I start the jail i get spammed with the following messages in the console log. [apologies for formatting - it looks good when I am editing the issue - so I have added some extra spaces]

`Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered blocking state

Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered disabled state

Sep 28 21:45:03 newnas.sendarian.co.uk kernel: device vb-docker-jail entered promiscuous mode

Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered blocking state

Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered listening state

Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered disabled state

Sep 28 21:45:08 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): host0: link becomes ready

Sep 28 21:45:08 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered blocking state

Sep 28 21:45:08 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered listening state

Sep 28 21:45:23 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered learning state

Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered blocking state

Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered disabled state

Sep 28 21:45:25 newnas.sendarian.co.uk kernel: device veth9aba5b5 entered promiscuous mode

Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered blocking state

Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered forwarding state

Sep 28 21:45:25 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready

Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered disabled state

Sep 28 21:45:27 newnas.sendarian.co.uk kernel: eth0: renamed from vethe8b166a

Sep 28 21:45:27 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth9aba5b5: link becomes ready

Sep 28 21:45:27 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered blocking state

Sep 28 21:45:27 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered forwarding state

Sep 28 21:45:38 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered forwarding state

Sep 28 21:45:38 newnas.sendarian.co.uk kernel: br0: topology change detected, sending tcn bpdu

Sep 28 21:46:52 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered blocking state

Sep 28 21:46:52 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered disabled state

Sep 28 21:46:52 newnas.sendarian.co.uk kernel: device veth9390273 entered promiscuous mode

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: eth0: renamed from veth989bad2

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth9390273: link becomes ready

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered blocking state

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered forwarding state

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): br-be2b02c1ea85: link becomes ready

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered disabled state

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: veth989bad2: renamed from eth0

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered disabled state

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: device veth9390273 left promiscuous mode

Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered disabled state`

I start docker-jail with the following command (actually "./jlmakr.py start docker-jail")
systemd-run --property=KillMode=mixed --property=Type=notify --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=Delegate=yes --property=TasksMax=infinity --collect --setenv=SYSTEMD_NSPAWN_LOCK=0 --unit=jlmkr-docker-jail --working-directory=./jails/docker-jail '--description=My nspawn jail docker-jail [created with jailmaker]' --setenv=SYSTEMD_SECCOMP=0 --property=DevicePolicy=auto -- systemd-nspawn --keep-unit --quiet --boot --machine=docker-jail --directory=rootfs --capability=all '--system-call-filter=add_key keyctl bpf' --network-bridge=br0 --resolv-conf=bind-host

The jail has its own IP address on my network.  I am using advanced networking (from the manual) to give the jail its own IP seperate from the host

docker-jail config file:
`docker_compatible=1
gpu_passthrough_intel=0
gpu_passthrough_nvidia=0
systemd_nspawn_user_args=--network-bridge=br0 --resolv-conf=bind-host
# You generally will not need to change the options below
systemd_run_default_args=--property=KillMode=mixed --property=Type=notify --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=Delegate=yes --property=TasksMax=infinity --collect --setenv=SYSTEMD_NSPAWN_LOCK=0
systemd_nspawn_default_args=--keep-unit --quiet --boot`
--------------------------------------------------------------------------------

80-container-host0.network file in container

`[Match]
Virtualization=container
Name=host0

[Network]
DHCP=false
Address=192.168.38.191/24
Gateway=192.168.38.15
LinkLocalAddressing=no
LLDP=yes
EmitLLDP=customer-bridge

[DHCP]
UseTimezone=yes
`

Anything else I can provide?

**Comment by aardvarkl** [comment]
Hmmm, formatting of the log file is wrong - can't seem to fix it

`Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered blocking state
Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered disabled state
Sep 28 21:45:03 newnas.sendarian.co.uk kernel: device vb-docker-jail entered promiscuous mode
Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered blocking state
Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered listening state
Sep 28 21:45:03 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered disabled state
Sep 28 21:45:08 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): host0: link becomes ready
Sep 28 21:45:08 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered blocking state
Sep 28 21:45:08 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered listening state
Sep 28 21:45:23 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered learning state
Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered blocking state
Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered disabled state
Sep 28 21:45:25 newnas.sendarian.co.uk kernel: device veth9aba5b5 entered promiscuous mode
Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered blocking state
Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered forwarding state
Sep 28 21:45:25 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
Sep 28 21:45:25 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered disabled state
Sep 28 21:45:27 newnas.sendarian.co.uk kernel: eth0: renamed from vethe8b166a
Sep 28 21:45:27 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth9aba5b5: link becomes ready
Sep 28 21:45:27 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered blocking state
Sep 28 21:45:27 newnas.sendarian.co.uk kernel: docker0: port 1(veth9aba5b5) entered forwarding state
Sep 28 21:45:38 newnas.sendarian.co.uk kernel: br0: port 3(vb-docker-jail) entered forwarding state
Sep 28 21:45:38 newnas.sendarian.co.uk kernel: br0: topology change detected, sending tcn bpdu
Sep 28 21:46:52 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered blocking state
Sep 28 21:46:52 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered disabled state
Sep 28 21:46:52 newnas.sendarian.co.uk kernel: device veth9390273 entered promiscuous mode
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: eth0: renamed from veth989bad2
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth9390273: link becomes ready
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered blocking state
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered forwarding state
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): br-be2b02c1ea85: link becomes ready
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered disabled state
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: veth989bad2: renamed from eth0
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered disabled state
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: device veth9390273 left promiscuous mode
Sep 28 21:46:53 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth9390273) entered disabled state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered blocking state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered disabled state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: device veth05e6fbf entered promiscuous mode
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered blocking state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered forwarding state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered disabled state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: eth0: renamed from veth027a9d5
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth05e6fbf: link becomes ready
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered blocking state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered forwarding state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered disabled state
Sep 28 21:52:12 newnas.sendarian.co.uk kernel: veth027a9d5: renamed from eth0
Sep 28 21:52:13 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered disabled state
Sep 28 21:52:13 newnas.sendarian.co.uk kernel: device veth05e6fbf left promiscuous mode
Sep 28 21:52:13 newnas.sendarian.co.uk kernel: br-be2b02c1ea85: port 1(veth05e6fbf) entered disabled state`

**Comment by Jip-Hop** [comment]
But is there actually a problem? I mean, does networking not work well? I hadn't noticed before but I see similar messages in the console log after a reboot and start of the jail. But then it seems to settle. I haven't seen these messages in the log for the past 5 days since my last reboot.

I suggest you investigate by creating a VM from the TrueNAS web gui and attach it to your bridge interface. Do you see similar messages? Then it doesn't seem to be specific to `jailmaker`.

**Comment by aardvarkl** [comment]
I have a VM attached via the bridge. I had the jailmaker jail turned off for a few days - no messages. Once I turned it back on again - message spam

The message spam is continuous

**Comment by Jip-Hop** [comment]
That's a bummer. I have no idea what's causing it and I don't experience the issue myself either. I've been running jailmaker for months in combination with the bridge interface (and the occasional VM attached to the same bridge). My jail is assigned the IP address via DHCP (looks like you assigned a static one?) and I have disabled ipv6 on my router (devices are assigned ipv4 only via DHCP).

Have you tried using macvlan instead of the bridge?

**Comment by aardvarkl** [comment]
I have not. I was thinking of trying a different interface but I seem to have disabled all the "unused" interfaces - which means a machine out job to move a jumper, and I am not at home atm.

**Comment by Jip-Hop** [comment]
Why would you want to use NFS inside the jail (or containers inside the jail). A big reason of making jailmaker is that you can bind mount storage directly without a network protocol like NFS.

**Comment by aardvarkl** [comment]
Because I can then migrate (move) containers between different environments and the stack file remains identical between hosts

**Comment by Jip-Hop** [comment]
I'd always use direct access (bind mounts) over NFS if the data is on the same host as the containers, for the best performance. But if you want to use NFS I can see why macvlan is inconvenient.

Have you tried using the simple (default) host networking instead of the more complicated bridge networking? Maybe that could work for your situation?

W.r.t. finding the cause of this issue. Perhaps shutdown all jails and try to create and start a fresh jail (without installing anything in it). Follow the bridge networking setup exactly as in the Readme and let DHCP assign the IP address. Please confirm if it works now with this most minimal setup.

**Comment by aardvarkl** [comment]
OK - shutdown my original jail
Created a new jail, without docker support and with the additional flags --network-macvlan=br0 --resolv-conf=bind-host

Starting the jail creates a load of messages in the console log - which I would have thought is to be expected as the jail attaches to the bridge and I now have an IP address via DHCP. I started the jail at 06.24.xx 

I will follow up by editing this message in a little while

**Comment by Jip-Hop** [comment]
Glad to hear macvlan works fine. Please try the most minimal scenario again but this time with `--network-bridge=br0`. Please do not create/edit `80-container-host0.network` at this moment.

**Comment by aardvarkl** [comment]
Thats what I am doing. 
--network-bridge=br0 and the dns bit as well.

**Comment by Jip-Hop** [comment]
And what do you see in the logs?

**Comment by aardvarkl** [comment]
No log spam

**Comment by aardvarkl** [comment]
Must be the jail itself - not what I was expecting

**Comment by Jip-Hop** [comment]
Maybe you had a docker container inside the jail which was in a start/crash loop? But I don't think there's anything I can/should fix on the jailmaker side of things.

**Comment by aardvarkl** [comment]
I agree - further testing shows its docker / portainer doing this.
