### ISSUE TITLE
What happens on a jlmkr.py start jail and (more importantly) on a jlmkr.py stop jail

### ISSUE THREAD

**Issue by aardvarkl** [Jip-Hop/jailmaker#37]
I honestly have no idea if this is an issue or not. I think its mostly a lack of knowledge

With a normal VM, the guest runs, stops and starts in a normal manner. If you just kill the VM its the equivalent of turning the power off. When you turn it on it boots up in x seconds / minutes and all is good. Shutting down takes an equivalent amount of time

Jailmaker / I guess systemd-container or whatever its called doesn't seem to do that.

Startup is, or seems to be effectively immediate
Just as is shutdown. And if I am logged in via SSH to the jail and type shutdown now - the jail just vanishes.

So on to my question - is this data safe? Or am I just hitting the power off button each time?
[Note it does seem that portainer takes a  little while to start up - but that may be the IP address taking 20 seconds bit]

**Comment by Jip-Hop** [comment]
That's normal behavior for containers. A VM needs to init a whole lot more. A VM has its own kernel for example, containers use the host kernel. Starting a container with `docker run` is instantaneous too. You don't need to worry about it being like 'pulling the plug'.

**Comment by aardvarkl** [comment]
Thank you
