### ISSUE TITLE
Bind /proc

### ISSUE THREAD

**Issue by SRBGod** [Jip-Hop/jailmaker#44]
Is there a way to bind /proc/sys to be RW inside of the jails? I am not able to start k3s because it keeps telling me that /proc/sys/vm is read only even though I —bind=/proc

```

```
Oct 16 16:57:02 k1 k3s[7490]: I1016 16:57:02.806728    7490 state_mem.go:35] "Initializing new in-memory state store"
Oct 16 16:57:02 k1 k3s[7490]: I1016 16:57:02.806970    7490 state_mem.go:75] "Updated machine memory state"
Oct 16 16:57:02 k1 k3s[7490]: E1016 16:57:02.807649    7490 kubelet.go:1480] "Failed to start ContainerManager" err="open /proc/sys/vm/overcommit_memory: read-only file system"
Oct 16 16:57:02 k1 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 16:57:02 k1 systemd[1]: k3s.service: Failed with result 'exit-code'.
Oct 16 16:57:02 k1 systemd[1]: k3s.service: Consumed 7.181s CPU time.
```

```

**Comment by Jip-Hop** [comment]
I don't know if there's a way to do it. If there is I expect it will be documented in the systemd-nspawn docs.

But have you tried to set overcommit_memory on the host to the appropriate value? Perhaps k3s won't need to set this value from inside the jail when it's already correct.

**Comment by SRBGod** [comment]
Yes, I tried changing it with no luck unfortunately.

**Comment by Jip-Hop** [comment]
Have you tried these settings/values:
https://docs.k3s.io/security/hardening-guide#set-kernel-parameters

If that works I actually recommend to set these values persistently from the TrueNAS SCALE WebGUI.

**Comment by SRBGod** [comment]
Trying both now, first with persistent kernel parameters.

**Comment by SRBGod** [comment]
Changing the kernel parameters on the host solved the issue.
