### ISSUE TITLE
'shell' command doesn't login shell

### ISSUE THREAD

**Issue by simonbcn** [Jip-Hop/jailmaker#48]
When I enter in shell with `jlmkr shell archLinux` does not run it as a login-shell and therefore does not run the shell user's environment files (_e.g., in my case, ~/.bashrc_).
Is this intentional?
How can I solve it?

**Comment by Lockszmith-GH** [comment]
don't know what is going on with jails, as I've not implemented yet, but for bash to run as a login shell it needs to be invoked with `-l`, is this somehitng you can change?

**Comment by Jip-Hop** [comment]
Hi Simon. My advice is to look up the `shell` and `login` commands in the `machinectl` manual: https://manpages.debian.org/bookworm/systemd-container/machinectl.1.en.html.

The `jlmkr shell` command is just a shortcut for `machinectl shell`. But for your scenario perhaps `machinectl login` would be desired. Alternatively you could install OpenSSH Server and login through ssh instead.

Or perhaps you could just use `jlmkr shell` and switch to a different user with `su -l username`. The `-l` flag [will 
start the shell as a login shell with an environment similar to a real login](https://man7.org/linux/man-pages/man1/su.1.html).

I'm going to close the issue as I think you'll be able to solve this.
