### ISSUE TITLE
how execute system user units at boot inside jail?

### ISSUE THREAD

**Issue by simonbcn** [Jip-Hop/jailmaker#49]
Arch Linux in jail.
I have installed `qbittorrent-nox` from Arch official repositories in jail.
I've changed last line of this service from:
```
[Install]
WantedBy=multi-user.target
```
to
```
[Install]
WantedBy=default.target
```
and I enabled the service `systemctl enable qbittorrent-nox@apps`. 

But when I restart the virtual machine, it doesn't start the service. What is wrong?

**Comment by simonbcn** [comment]
`apps` has the same `uid`/`gid` than Truenas Scale host.

**Comment by Jip-Hop** [comment]
I can't help you with this as I'm not using Arch Linux myself. Besides this issue is out of scope of the jailmaker project.
