### ISSUE TITLE
Default behavior of disabling LinkLocalAddressing for bridge/macvlan breaks IPv6 inside container

### ISSUE THREAD

**Issue by bcat** [Jip-Hop/jailmaker#55]
By default, Jailmaker [disables link-local addressing](https://github.com/Jip-Hop/jailmaker/blob/fd5d987de4eff96b3821016625f0b0dc7779ba89/jlmkr.py#L761-L788) for bridge and macvlan networks. The comment says that `LinkLocalAddressing=yes` interferes with DHCP address assignment.

For IPv4, this isn't a big deal, but for IPv6, [link-local addressing is required](https://en.wikipedia.org/wiki/Link-local_address#IPv6). Otherwise, the container won't be able to get an IPv6 address via SLAAC or DHCPv6. This effectively breaks IPv6

I would suggest the following changes to `jlmkr create`:

1. Set `LinkLocalAddressing=ipv6` when the container is created. This [is actually the default in systemd anyway](https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html#LinkLocalAddressing=), and keeps link-local disabled for IPv4 (which seems to have been Jailmaker's original intent), but enables it for IPv6 (fixing IPv6 networking in the container).
2. Set `DHCP=yes` instead of `DHCP=ipv4` since there's no longer any conflict with the `LinkLocalAddressing` setting. (In any case, SLAAC or DHCPv6 will still be used appropriately based on the router advertisements the container OS receives.)

With this configuration on a Debian Bookworm container in a TrueNAS SCALE Cobia host, everything seems to work fine. The container receives an IPv4 address (from DHCP), an IPv6 link-local address, and an IPv6 global address (from SLAAC).

**Comment by Jip-Hop** [comment]
Thanks! Would you mind creating a pull request for this?
