### ISSUE TITLE
Latest version from main branch doesnt works

### ISSUE THREAD

**Issue by maxx-ukoo** [Jip-Hop/jailmaker#59]
I have updated TrueNAS to TrueNAS-SCALE-22.12.4.2.
Latest script version from main branch can't fix systemd-nspawn link with error:

>   File "/mnt/pool/jailmaker/jlmkr.py", line 669
    End":36938,"fullyQualifiedName":"startup_jails","identUtf16":{"start":{"lineNumber":1035,"utf16Col":4},"end":{"lineNumber":1035,"utf16Col":17}},"extentUtf16":{"start":{"lineNumber":1035,"utf16Col":0},"end":{"lineNumber":1038,"utf16Col":35}}},{"name":"main","kind":"function","identStart":36945,"identEnd":36949,"extentStart":36941,"extentEnd":41024,"fullyQualifiedName":"main","identUtf16":{"start":{"lineNumber":1041,"utf16Col":4},"end":{"lineNumber":1041,"utf16Col":8}},"extentUtf16":{"start":{"lineNumber":1041,"utf16Col":0},"end":{"lineNumber":1159,"utf16Col":32}}}]}},"copilotInfo":null,"copilotAccessAllowed":false,"csrf_tokens":{"/Jip-Hop/jailmaker/branches":{"post":"Q-CcRBfYYIvyxarS7APvCfojLo3ZlKWOxsmuKl83rlslK8xEawmean6ru_GvKdqjZ-ulRpin8icXPN6s2tHvsA"},"/repos/preferences":{"post":"38jXX8F5Qzmo_mCvsxcfYtk3XE1StJUxTCc8dfbDnm8rzpmg-iRSbiO_ktXHJZ_7DwoXfKhA-_afKK9oeb1cBw"}}},"title":"jailmaker/jlmkr.py at main · Jip-Hop/jailmaker"}
               ^
IndentationError: unexpected indent

Version from release 1.0.0 works ok for me.

**Comment by Jip-Hop** [comment]
Strange. Line 669 is just a comment. How did you download and install this release? Please post the exact steps and show minimal example of how to reproduce this. Also try running the jlmkr.py script manually instead of scheduled through the post init command.

**Comment by maxx-ukoo** [comment]
I tried to download version from master again - it works now.  Sorry
