### ISSUE TITLE
docker won't run because of ro cgroups directory

### ISSUE THREAD

**Issue by antifessional** [Jip-Hop/jailmaker#71]
TrueNAS-SCALE-22.02.4
    jailmaker - latest
    jail client: debian 
    network: bridge

I have docker_compatible=1 in the config file. When trying to run docker in a jail, I get error
``` unable to start container process: unable to apply cgroup configuration: mkdir /sys/fs/cgroup/cpuset/docker: read-only file system ```

**Comment by Jip-Hop** [comment]
First upgrade to the most recent version of SCALE then try again.

**Comment by Jip-Hop** [comment]
Also see:
https://github.com/Jip-Hop/jailmaker/discussions/67
