### ISSUE TITLE
README and loading nvidia drivers

### ISSUE THREAD

**Issue by joeroback** [Jip-Hop/jailmaker#78]
The readme says
```
[ ! -f /dev/nvidia-uvm ] && modprobe nvidia-current-uvm && /usr/bin/nvidia-modprobe -c0 -u
```

but doesn't that mean if the file, `/dev/nvidia-uvm`  does NOT exist, try and load the nvidia-current-urm driver? Should it be
```
[ -f /dev/nvidia-uvm ] && modprobe nvidia-current-uvm && /usr/bin/nvidia-modprobe -c0 -u
```
?

**Comment by Jip-Hop** [comment]
Thanks for the suggestion. I don't have an nvidia GPU so I need to rely on the community to contribute documentation and test the nvidia GPU passthrough.

Maybe you could have a look at this discussion:
https://github.com/Jip-Hop/jailmaker/discussions/74

And try out the latest jailmaker from the develop branch. I'll probably make a new release in the upcoming weeks.

**Comment by joeroback** [comment]
oh yea, sorry, this is my mistake. you want to check that the device does not exist, meaning the driver hasn't been loaded yet.
