### ISSUE TITLE
Create ZFS dataset for each jail

### ISSUE THREAD

**Issue by Jip-Hop** [Jip-Hop/jailmaker#80]
### Discussed in https://github.com/Jip-Hop/jailmaker/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **Kailee71** January  2, 2024</sup>
HI all,

at the moment jails "just" live in subdirectories of the jailmaker dataset/zvol. Would it be possible to create a seperate dataset (or zvol for that matter) per jail at creation time? This would enable very straightforward and reliable backup strategies though the snapshot and replication tasks already included in Scale. Would love to see this included.</div>

<hr>

Instead of creating a new directory inside the jails directory, automatically create a new ZFS dataset when creating a new jail. This allows for creating snapshots if individual jails, with custom retention rules. Implement it in a backwards compatible way, so `jlmkr remove` will continue to work with jails which were created as normal directories (instead of datasets) in the jails dir.

I'm opening this issue to keep track of feature requests/improvements. I have no plans to implement this a.t.m. but contributions are welcome.

**Comment by templehasfallen** [comment]
This is a great addition - I came here for the same reason.

As for the process mentioned [here](https://github.com/Jip-Hop/jailmaker/discussions/68#discussioncomment-8001905), forego this, maybe a command-line option can be added to Jailmaker to override the directory creation/force install into an existing directory? 

The above would allow for creation of a jail in an existing directory which in this case would be an already created dataset.

**Comment by templehasfallen** [comment]
Actually I went ahead and added support for existing ZFS datasets

https://github.com/Jip-Hop/jailmaker/pull/113

**Comment by templehasfallen** [comment]
Full support now added with #118
