### ISSUE TITLE
Snapshot/rollback command

### ISSUE THREAD

**Issue by Jip-Hop** [Jip-Hop/jailmaker#82]
Consider implementing a `jlmkr snapshot` and `jlmkr rollback` method.

Blocked by: #80.

**Comment by chronicom** [comment]
Hi I am not sure how do you plan to implment this. But in my opionin, the easiest way is to create a dataset under /jails . This way we can take advantage of ZFS under hood like the how the VM's storage is created. This of course will need to make /jails a dataset as well.  But then we can snapshot or restore the dataset simply use TN 's web UI .

**Comment by Jip-Hop** [comment]
Thanks for the suggestion. You're right from the web GUI would be the easiest way to do this. I currently have no plans to implement #80 but contributions are welcome.

**Comment by Jip-Hop** [comment]
Now that a dataset is created for each jail in [v1.1.4](https://github.com/Jip-Hop/jailmaker/releases/tag/v1.1.4) this can be done using the web UI or using native zfs commands. I've considered implementing these commands directly in jailmaker but I don't see the need for this currently. So I'm closing this issue.
