### ISSUE TITLE
TrueNAS 24.04 read only file system

### ISSUE THREAD

**Issue by spusuf** [Jip-Hop/jailmaker#87]
The TrueNAS Scale 24.04 Dragonfish beta appears to have moved from a permissive file system to a read only filesystem. This prohibits creating symlinks, enabling apt, among others. 

The jailmaker install outputs
```
root@truenas[/mnt/hermes/jailmaker]# ./jlmkr.py install
systemd-nspawn is already installed.
Creating symlink /usr/local/sbin/jlmkr to /mnt/hermes/jailmaker/jlmkr.py.
Traceback (most recent call last):
  File "/mnt/hermes/jailmaker/./jlmkr.py", line 1165, in <module>
    main()
  File "/mnt/hermes/jailmaker/./jlmkr.py", line 1117, in main
    install_jailmaker()
  File "/mnt/hermes/jailmaker/./jlmkr.py", line 1027, in install_jailmaker
    os.symlink(SCRIPT_PATH, target)
OSError: [Errno 30] Read-only file system: '/mnt/hermes/jailmaker/jlmkr.py' -> '/usr/local/sbin/jlmkr'
root@truenas[/mnt/hermes/jailmaker]# 
```
Same outcome when manually attempting to add chmod +x to apt*

Personally it feels like iX is resisting any changes to the "correct" way of using their platform. I think I'm going to rollback, export all my configs and then switch to ProxmoxVE. Although this project has been absolutely incredible to use and I was planning on contributing more, diagnosing issues every release has made me think "why am i even doing this?" Proxmox has better container performance, usability, and I can just add a network share from Proxmox. 

Happy to revisit this project in the future. Ideally iX would give up on their horrid, lossy, unperformant k8s server and move to containers natively. If that ever happens I will gladly switch to TrueNAS Scale for the rest of my server's lifetime, but this may be the end of my TrueNAS journey unfortunately.

**Comment by Jip-Hop** [comment]
Try the jailmaker version on from the develop branch. It should work with the readonly filesystem in 24.04. The goal of jailmaker was to not have to modify the root filesystem so this was not a big shock to me. And since systemd-nspawn is now officially included I think the situation is actually improving :)

https://github.com/truenas/scale-build/pull/573

**Comment by Jip-Hop** [comment]
Support for the TrueNAS 24.04 read only filesystem is planned for the next release of jailmaker which should be in time for the release of TrueNAS 24.04 in April (it basically comes down to using a shell alias instead of a symlink to conveniently call `jlmkr`).
