### ISSUE TITLE
How to set a static IP address(macvlan) in config file?

### ISSUE THREAD

**Issue by rexzhang** [Jip-Hop/jailmaker#89]
How to set a static IP address when using `--network-macvlan` mode. Currently, I do this by entering the container and running the following command:
```shell
ip link set mv-enp4s0 up

ip addr add 192.168.1.2/24 dev mv-enp4s0
ip route add default via 192.168.1.1 dev mv-enp4s0
```

**Comment by Jip-Hop** [comment]
I think you can follow the advice here:
https://unix.stackexchange.com/questions/517199/systemd-nspawn-machinectl-and-macvlan

**Comment by Jip-Hop** [comment]
Closed as this is not an issue and not specific to jailmaker.
