### ISSUE TITLE
Host networking - TrueNAS UI binding 0.0.0.0 no matter what?

### ISSUE THREAD

**Issue by AdamCarballo** [Jip-Hop/jailmaker#92]
Hello,

I've been trying to setup docker for a bit inside a jail (all working nicely for the most part!) - but I'm a bit stuck with the current networking setup.

I would like to keep host networking (the deafult), but as you mention TrueNAS will bind to `0.0.0.0` for it's UI, blocking ports `80` and `443`.

I tried to do the following from the README: 
> To workaround this issue when using host networking, you may disable DHCP and add several static IP addresses (Aliases) through the TrueNAS web interface. **If you setup the TrueNAS web interface to only listen on one of these IP addresses, the ports on the remaining IP addresses remain available for the jail to listen on.**

I disabled DHCP, added a new Alias IP and marked that IP to be the "Web Interface IPv4 Address" in System > General > GUI. Sadly, even though it works (I can mark one or the other, and only that specific IP will show the UI) my docker container can't bind to `0.0.0.0:80`.

I was able to bind the container once while the TrueNAS UI was restarting, which broke the TrueNAS UI (essentially, it didn't manage to bind to anything) - so it seems that no matter what IP you set, it keeps binding or occupying `0.0.0.0`?

The tooltip in TrueNAS mentions:
> The built-in HTTP server binds to the wildcard address of 0.0.0.0 (any address) and issues an alert if the specified address becomes unavailable.

So maybe there's no way to stop TrueNAS anymore? I didn't check how it looks in older versions.

Have you maybe managed to get this working recently, or am I missing some obvious setting change to stop TrueNAS from holding `0.0.0.0:80` hostage, or there's no way to bind a container to `0.0.0.0` and I should specify the IP alias directly in the container? Thanks!

**Comment by Jip-Hop** [comment]
I don't think you can bind to 0.0.0.0:80 in this case as this would bind to all ip addresses available to the host (wildcard) including the one you've specified for the TrueNAS web interface. So you need to bind specifically to the ip address which is NOT used by the TrueNAS web interface.

**Comment by AdamCarballo** [comment]
Yeah, that's what I ended up doing after some more testing.
Thanks for confirming there's no way around it 🙂

**Comment by Lockszmith-GH** [comment]
I'm running Cobia with Jailmaker, and everything is bound per instructions.

TrueNAS SCALE Web UI is listening on `192.168.2.13` ports `80`/`443`

On my jail is running with host networking, I have an AdGuard Home running as a docker container with host networking.
The service is bound to `192.168.2.53` and is serving the web interface on ports `80`/`443` and DNS on `53` (UDP and TCP)

TrueNAS SCALE's Kubernetes node is bound to `192.168.2.14`
Traefik TrueCharts App is listening on `192.168.2.14` ports `80`/`443`

It looks like this:

### Network settings
![image](https://github.com/Jip-Hop/jailmaker/assets/905716/895bbe0a-d8e8-46de-9220-61f820d5ba34)

### General Settings
![image](https://github.com/Jip-Hop/jailmaker/assets/905716/53075e23-7bae-4895-bcd6-4c30435cd537)

### With Kubernetes
I also use iX Apps (Kubernetes), with TrueChart's traefik listening on ports 80 and 443, just on a different IP address (utilizing their MetalLB implementation).
It looks like this:

#### Apps -> Advanced Settings:
![image](https://github.com/Jip-Hop/jailmaker/assets/905716/63733224-dde2-49fa-a337-9510b061cd7f)

#### Apps -> metallb-conf:
![image](https://github.com/Jip-Hop/jailmaker/assets/905716/fb99f50d-3aa8-49ea-9323-298cd6c7c839)

#### Apps -> Traefik -> Network Settings
![image](https://github.com/Jip-Hop/jailmaker/assets/905716/99b27c5b-bc87-428b-a7ff-fe9321a07dad)

Hope this helps

**Comment by Jip-Hop** [comment]
@Lockszmith-GH you're not running into (iptables) conflicts when using docker in jailmaker with host networking alongside Apps?

**Comment by Jip-Hop** [comment]
Maybe you haven't run into them yet because your only container is also using host networking. I don't know for sure. Have a look at the [docker firewall documentation](https://docs.docker.com/network/packet-filtering-firewalls/).

I generally recommend to use docker inside a jail which is using macvlan or bridge networking, so the jail can manage iptables in an isolated network namespace without wiping iptables rules on the host.

**Comment by Lockszmith-GH** [comment]
I couldn't use macvlan because the DNS needs to serve TrueNAS apps hosted on the same machine.

**Comment by Jip-Hop** [comment]
Bridge networking is the best in that scenario I suppose. Although [I read there's a way](https://wiki.archlinux.org/title/systemd-nspawn#Use_a_%22macvlan%22_or_%22ipvlan%22_interface) to make the jail communicate with the host even when using macvlan networking.

Some more reading:
https://blog.thelazyfox.xyz/give-access-to-host-from-docker-containers-macvlan/
https://gist.github.com/xirixiz/ecad37bac9a07c2a1204ab4f9a17db3c
https://community.synology.com/enu/forum/15/post/120118
https://kcore.org/2020/08/18/macvlan-host-access/
