### ISSUE TITLE
not able to make Apache listen on SSL inside jailmaker

### ISSUE THREAD

**Issue by Bylemon** [Jip-Hop/jailmaker#99]
I've installed Debian 12 with jlmkr, under TrueNAS and I can get it to listen on HTTP, but not on HTTPS. 
Not sure if it is something specific to my config, but I can't see any errors in the logs.

Is it some restriction of how jailmaker works?

**Comment by Lockszmith-GH** [comment]
Are you using host networking?

Most likely there is a conflict with the binding of your service inside the jail and a service on the host.

If so, make sure you're services inside and outside the jail are not listening on 0.0.0.0:443.
or alternativley, create the jail with [bridge networking](https://github.com/Jip-Hop/jailmaker/blob/main/NETWORKING.md).

**Comment by Jip-Hop** [comment]
Closing this as not an issue. This is documented here: https://github.com/Jip-Hop/jailmaker?tab=readme-ov-file#networking
